//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhfood_material
    {
        /// <summary>
        /// 商家菜品原料组成表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 菜品ID
        /// </summary>
        public string FoodID { get; set; }
        /// <summary>
        /// 菜品名称
        /// </summary>
        public string FoodName { get; set; }
        /// <summary>
        /// 材料ID
        /// </summary>
        public string MaterialID { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public decimal CountNum { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 材料成本归属（1主料2辅料）
        /// </summary>
        public int MaterialPriceType { get; set; }
        /// <summary>
        /// 材料成本
        /// </summary>
        public decimal MateriaPrice { get; set; }
        /// <summary>
        /// 菜品规格ID
        /// </summary>
        public string FoodSpecificationsID { get; set; }
        /// <summary>
        /// 菜品规格名称
        /// </summary>
        public string FoodSpecificationsName { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        public string WareHouseID { get; set; }
    }
}


