//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhmaterialtype
    {
        /// <summary>
        /// 店铺仓库材料分类表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 分类名
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 图片
        /// </summary>
        public string ImgUrl { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 创建者ID
        /// </summary>
        public string CreateSellerID { get; set; }
        /// <summary>
        /// 材料分类父ID
        /// </summary>
        public string ParentID { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 是否可用 删除之后不可用
        /// </summary>
        public bool IsAvailable { get; set; }
    }
}


