//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderrequisition
    {
        /// <summary>
        /// 仓库调拨申请表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 申请名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 预算金额
        /// </summary>
        public Nullable<decimal> PriceBudget { get; set; }
        /// <summary>
        /// 实际金额
        /// </summary>
        public Nullable<decimal> PriceReal { get; set; }
        /// <summary>
        /// 申请人ID
        /// </summary>
        public string ApplySellerID { get; set; }
        /// <summary>
        /// 申请简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 订单状态（1审批中2审批不通过3审批通过采购中4采购完成）
        /// </summary>
        public Nullable<int> OrderState { get; set; }
        /// <summary>
        /// 审批人ID
        /// </summary>
        public string ApproveSellerID { get; set; }
        /// <summary>
        /// 审批内容
        /// </summary>
        public string ApproveContents { get; set; }
        /// <summary>
        /// 审批时间
        /// </summary>
        public Nullable<System.DateTime> ApproveTime { get; set; }
        /// <summary>
        /// 实际收操作人ID
        /// </summary>
        public string OperationSellerID { get; set; }
        /// <summary>
        /// 操作时间
        /// </summary>
        public Nullable<System.DateTime> OperationTime { get; set; }
        /// <summary>
        /// 接收店铺ID
        /// </summary>
        public string ToShopID { get; set; }
        /// <summary>
        /// 领取人签字图片
        /// </summary>
        public string ToShopSellerImg { get; set; }
        /// <summary>
        /// 接收店铺接收人名字
        /// </summary>
        public string ToShopSellerName { get; set; }
        /// <summary>
        /// 接收人手机号
        /// </summary>
        public string ToShopSellerPhone { get; set; }
    }
}


