//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderinside
    {
        /// <summary>
        /// 仓库内部领料申请表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 申请名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 出库方式 1内部领料 
        /// </summary>
        public int InsideMode { get; set; }
        /// <summary>
        /// 出库金额
        /// </summary>
        public decimal InsideMoney { get; set; }
        /// <summary>
        /// 出库时间
        /// </summary>
        public System.DateTime InsideTime { get; set; }
        /// <summary>
        /// 申请人ID
        /// </summary>
        public string ApplySellerID { get; set; }
        /// <summary>
        /// 申请简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 订单状态（1进行中 2已完成 3已取消）
        /// </summary>
        public int OrderState { get; set; }
        /// <summary>
        /// 实际领取操作人ID
        /// </summary>
        public string OperationSellerID { get; set; }
        /// <summary>
        /// 领取操作时间
        /// </summary>
        public Nullable<System.DateTime> OperationTime { get; set; }
        /// <summary>
        /// 领取人签字图片
        /// </summary>
        public string OperationImg { get; set; }
        /// <summary>
        /// 出料仓库
        /// </summary>
        public string FromWareHouseID { get; set; }
        /// <summary>
        /// 领料仓库
        /// </summary>
        public string ToWareHouseID { get; set; }
    }
}


