//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhordercheck
    {
        /// <summary>
        /// 仓库盘点表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 申请名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 申请人ID
        /// </summary>
        public string ApplySellerID { get; set; }
        /// <summary>
        /// 申请简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 订单状态（1提交盘点单2盘点完成）
        /// </summary>
        public int OrderState { get; set; }
        /// <summary>
        /// 盘点人ID
        /// </summary>
        public string OperationSellerID { get; set; }
        /// <summary>
        /// 盘点时间
        /// </summary>
        public Nullable<System.DateTime> OperationTime { get; set; }
		/// <summary>
        /// 校正人
        /// </summary>
        public string CheckSellerID { get; set; }
        /// <summary>
        /// 校正时间
        /// </summary>
        public Nullable<System.DateTime> CheckTime { get; set; }
        /// <summary>
        /// 仓库ID
        /// </summary>
        public string WareHouseID { get; set; }
    }
}


