//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderautooutsidefooddetail
    {
        /// <summary>
        /// 仓库自动出库单详情ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 仓库自动出库表ID
        /// </summary>
        public string OrderAutoOutsideID { get; set; }
        /// <summary>
        /// 菜品ID
        /// </summary>
        public string FoodID { get; set; }
        /// <summary>
        /// 菜品名称
        /// </summary>
        public string FoodName { get; set; }
        /// <summary>
        /// 是否套餐（1是0否）
        /// </summary>
        public int IsPackage { get; set; }
        /// <summary>
        /// 套餐名称
        /// </summary>
        public string PackageName { get; set; }
        /// <summary>
        /// 套餐规格
        /// </summary>
        public string PackageSpecifications { get; set; }
        /// <summary>
        /// 菜品数量
        /// </summary>
        public int FoodCount { get; set; }
        /// <summary>
        /// 菜品预算成本价格（这个是单一的价格）
        /// </summary>
        public decimal FoodPriceBudget { get; set; }
    }
}


