//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderrefunds
    {
        /// <summary>
        /// 仓库退货申请表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 申请名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 预算金额
        /// </summary>
        public decimal PriceBudget { get; set; }
        /// <summary>
        /// 实际金额
        /// </summary>
        public decimal PriceReal { get; set; }
        /// <summary>
        /// 申请人ID
        /// </summary>
        public string ApplySellerID { get; set; }
        /// <summary>
        /// 申请简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 订单状态（1提交审核2审核未通过3审核通过4退货出库签名5添加结算单10订单完成）
        /// </summary>
        public int OrderState { get; set; }
        /// <summary>
        /// 审批人ID
        /// </summary>
        public string ApproveSellerID { get; set; }
        /// <summary>
        /// 审批内容
        /// </summary>
        public string ApproveContents { get; set; }
        /// <summary>
        /// 审批时间
        /// </summary>
        public Nullable<System.DateTime> ApproveTime { get; set; }
        /// <summary>
        /// 出库库管ID
        /// </summary>
        public string OperationSellerID { get; set; }
        /// <summary>
        /// 出库时间,取货时间
        /// </summary>
        public Nullable<System.DateTime> OperationTime { get; set; }
        /// <summary>
        /// 仓库ID
        /// </summary>
        public string WareHouseID { get; set; }
        /// <summary>
        /// 退货供应商姓名
        /// </summary>
        public string RefundName { get; set; }
        /// <summary>
        /// 退货供应商电话
        /// </summary>
        public string RefundPhone { get; set; }
        /// <summary>
        /// 退货供应商签字图片
        /// </summary>
        public string RefundImage { get; set; }
        /// <summary>
        /// 供应商ID
        /// </summary>
        public string SupplierID { get; set; }
        /// <summary>
        /// 退款结算 0现金 1 欠款
        /// </summary>
        public int PayState { get; set; }
    }
}


