//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderstorage
    {
        /// <summary>
        /// ID
        /// </summary>
        public string ID { get; set; }

        public string ShopID { get; set; }
        /// <summary>
        /// 采购申请订单编号
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 订单类型（11采购入库12调拨入库13领料入库21退货出库22调拨出库31损耗）
        /// </summary>
        public string OrderType { get; set; }
        /// <summary>
        /// 0整单入库 1 分单
        /// </summary>
        public int TakeInWareHouseType { get; set; }
        /// <summary>
        /// 提交时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 库房id
        /// </summary>
        public string WareHouseID { get; set; }
        /// <summary>
        /// 供应商
        /// </summary>
        public string SupplierID { get; set; }
        /// <summary>
        /// 1现金2支付宝3微信4银行卡5支票6转账   9欠款10欠款已结清
        /// </summary>
        public int PayState { get; set; }
        /// <summary>
        /// 结算金额
        /// </summary>
        public decimal TotalMoney { get; set; }
        /// <summary>
        /// 提交人
        /// </summary>
        public string ApplySellerID { get; set; }
        /// <summary>
        /// 库管审核人
        /// </summary>
        public string CheckerID { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public int State { get; set; }
        /// <summary>
        /// 审核时间
        /// </summary>
        public Nullable<System.DateTime> CheckTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 分单次数
        /// </summary>
        public Nullable<int> Count { get; set; }
        /// <summary>
        /// 分单标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 库管签字图片
        /// </summary>
        public string CheckerImg { get; set; }
    }
}


