//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderautooutside
    {
        /// <summary>
        /// 仓库自动出库表ID（这个ID）
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 订单表ID
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 原料的出库金额
        /// </summary>
        public decimal PriceBudget { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 订单收入金额
        /// </summary>
        public decimal PriceOrder { get; set; }
        /// <summary>
        /// 支付完成时间（冗余字段）
        /// </summary>
        public System.DateTime PayFinishTime { get; set; }
        /// <summary>
        /// 出库单自动核减 0:未核减 1：已核减 2：核减失败
        /// </summary>
        public int? AutoCheckState { get; set; }
    }
}


