//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhorderautooutsidematerialdetail
    {
        /// <summary>
        /// 仓库材料自动出库单详情ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 仓库菜品自动出库表ID
        /// </summary>
        public string OrderFoodAutoOutsideID { get; set; }
        /// <summary>
        /// 材料ID
        /// </summary>
        public string MaterialID { get; set; }
        /// <summary>
        /// 材料名称
        /// </summary>
        public string MaterialName { get; set; }
        /// <summary>
        /// 材料成本归属（1主料2辅料）
        /// </summary>
        public int MaterialPriceType { get; set; }
        /// <summary>
        /// 材料单位成本(比如1千克5元)
        /// </summary>
        public decimal MateriaPrice { get; set; }
        /// <summary>
        /// 菜品规格ID
        /// </summary>
        public string MaterialSpecificationsID { get; set; }
        /// <summary>
        /// 菜品规格名称
        /// </summary>
        public string MaterialSpecificationsName { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 计量单位编号
        /// </summary>
        public string MaterialUnitID { get; set; }
        /// <summary>
        /// 计量单位名称
        /// </summary>
        public string MaterialUnitName { get; set; }
        /// <summary>
        /// 主计量单位编号
        /// </summary>
        public string MaterialMainUnitID { get; set; }
        /// <summary>
        /// 主计量单位名称
        /// </summary>
        public string MaterialMainUnitName { get; set; }
        /// <summary>
        /// 实际数量
        /// </summary>
        public decimal CountReal { get; set; }
        /// <summary>
        /// 实际数量(主计量单位)
        /// </summary>
        public decimal CountMainReal { get; set; }
        /// <summary>
        /// 报损数量
        /// </summary>
        public decimal LossCountReal { get; set; }
        /// <summary>
        /// 报损数量(主计量单位)
        /// </summary>
        public decimal LossCountMainReal { get; set; }
        /// <summary>
        /// 损耗率
        /// </summary>
        public decimal LossRate { get; set; }
        /// <summary>
        /// 总共数量
        /// </summary>
        public decimal TotalCountReal { get; set; }
        /// <summary>
        /// 总共数量(主计量单位)
        /// </summary>
        public decimal TotalCountMainReal { get; set; }
        /// <summary>
        /// 出料仓库
        /// </summary>
        public string FromWareHouseID { get; set; }
    }
}


