//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhsupplierbill
    {
        /// <summary>
        /// 材料供应商结账表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属用户ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 供应商ID
        /// </summary>
        public string SupplierID { get; set; }
        /// <summary>
        /// 变化类型（1增加2减少）
        /// </summary>
        public Nullable<int> ChangeType { get; set; }
        /// <summary>
        /// 变化的金额数
        /// </summary>
        public Nullable<decimal> ChangeValue { get; set; }
        /// <summary>
        /// 变化名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 改变后金额
        /// </summary>
        public Nullable<decimal> CurrentlyMoney { get; set; }
        /// <summary>
        /// 支付方式（1现金2支付宝3微信4银行卡5支票6转账）
        /// </summary>
        public Nullable<int> PayType { get; set; }
        /// <summary>
        /// 入库类型（0整单入库 1 分单）
        /// </summary>
        public int TakeinWarehouseType { get; set; }
        /// <summary>
        /// 支付完成凭证图片
        /// </summary>
        public string PayReadyImage { get; set; }
    }
}


