//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class swhshopstock
    {
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 是否开启库存(1是0否) 库存开启之后，需要在用户后台手动开启库存状态，方可使用
        /// </summary>
        public int IsBuyStock { get; set; }
        /// <summary>
        /// 是否可用 True可用 False不可用
        /// </summary>
        public bool IsAvailable { get; set; }
        /// <summary>
        /// 库存开通时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 库存到期时间
        /// </summary>
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// InitialStock
        /// </summary>
        public int InitialStock { get; set; }
    }
}


