//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class swhsuppliermoneydetail
    {
        /// <summary>
        /// 供应商支付流水表
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属用户ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 供应商ID
        /// </summary>
        public string SupplierID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal Before { get; set; }
        /// <summary>
        /// 变化类型（1增加2减少）
        /// </summary>
        public int Sign { get; set; }
        /// <summary>
        /// 变化的金额数
        /// </summary>
        public decimal Data { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal After { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 支付方式（1现金2支付宝3微信4银行卡5支票6转账 11欠款12 扣除欠款）
        /// </summary>
        public int PayType { get; set; }
        /// <summary>
        /// 付款详情方式（1进货2退货 3付款）
        /// </summary>
        public int MoneyType { get; set; }
        /// <summary>
        /// 对应的订单号
        /// </summary>
        public string OrderNumber { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 付款人
        /// </summary>
        public string OperationSellerID { get; set; }
    }
}


