//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Web.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://www.yrd.com/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yrd.com/", ConfigurationName="SR.FilesWebServiceSoap")]
    public interface FilesWebServiceSoap {
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/ImgFilesUp", ReplyAction="*")]
        YRD.Web.SR.ImgFilesUpResponse ImgFilesUp(YRD.Web.SR.ImgFilesUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/ImgFilesUp", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.ImgFilesUpResponse> ImgFilesUpAsync(YRD.Web.SR.ImgFilesUpRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/ImgFileUp", ReplyAction="*")]
        YRD.Web.SR.ImgFileUpResponse ImgFileUp(YRD.Web.SR.ImgFileUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/ImgFileUp", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.ImgFileUpResponse> ImgFileUpAsync(YRD.Web.SR.ImgFileUpRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesUpload_Thumb", ReplyAction="*")]
        YRD.Web.SR.FilesUpload_ThumbResponse FilesUpload_Thumb(YRD.Web.SR.FilesUpload_ThumbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesUpload_Thumb", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesUpload_ThumbResponse> FilesUpload_ThumbAsync(YRD.Web.SR.FilesUpload_ThumbRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesDelete", ReplyAction="*")]
        YRD.Web.SR.FilesDeleteResponse FilesDelete(YRD.Web.SR.FilesDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteResponse> FilesDeleteAsync(YRD.Web.SR.FilesDeleteRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesDeleteByPath", ReplyAction="*")]
        YRD.Web.SR.FilesDeleteByPathResponse FilesDeleteByPath(YRD.Web.SR.FilesDeleteByPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesDeleteByPath", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteByPathResponse> FilesDeleteByPathAsync(YRD.Web.SR.FilesDeleteByPathRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesDeleteByPaths", ReplyAction="*")]
        YRD.Web.SR.FilesDeleteByPathsResponse FilesDeleteByPaths(YRD.Web.SR.FilesDeleteByPathsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesDeleteByPaths", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteByPathsResponse> FilesDeleteByPathsAsync(YRD.Web.SR.FilesDeleteByPathsRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesExist", ReplyAction="*")]
        YRD.Web.SR.FilesExistResponse FilesExist(YRD.Web.SR.FilesExistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/FilesExist", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesExistResponse> FilesExistAsync(YRD.Web.SR.FilesExistRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 strkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/GetImageSize", ReplyAction="*")]
        YRD.Web.SR.GetImageSizeResponse GetImageSize(YRD.Web.SR.GetImageSizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/GetImageSize", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.GetImageSizeResponse> GetImageSizeAsync(YRD.Web.SR.GetImageSizeRequest request);
        
        // CODEGEN: 命名空间 http://www.yrd.com/ 的元素名称 rootpath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/ZipFileFromDirectory", ReplyAction="*")]
        YRD.Web.SR.ZipFileFromDirectoryResponse ZipFileFromDirectory(YRD.Web.SR.ZipFileFromDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yrd.com/ZipFileFromDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<YRD.Web.SR.ZipFileFromDirectoryResponse> ZipFileFromDirectoryAsync(YRD.Web.SR.ZipFileFromDirectoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImgFilesUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImgFilesUp", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.ImgFilesUpRequestBody Body;
        
        public ImgFilesUpRequest() {
        }
        
        public ImgFilesUpRequest(YRD.Web.SR.ImgFilesUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class ImgFilesUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rootpath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ThumbPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int height;
        
        public ImgFilesUpRequestBody() {
        }
        
        public ImgFilesUpRequestBody(string strkey, byte[] data, string filename, string rootpath, string ThumbPath, int width, int height) {
            this.strkey = strkey;
            this.data = data;
            this.filename = filename;
            this.rootpath = rootpath;
            this.ThumbPath = ThumbPath;
            this.width = width;
            this.height = height;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImgFilesUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImgFilesUpResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.ImgFilesUpResponseBody Body;
        
        public ImgFilesUpResponse() {
        }
        
        public ImgFilesUpResponse(YRD.Web.SR.ImgFilesUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class ImgFilesUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ImgFilesUpResult;
        
        public ImgFilesUpResponseBody() {
        }
        
        public ImgFilesUpResponseBody(bool ImgFilesUpResult) {
            this.ImgFilesUpResult = ImgFilesUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImgFileUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImgFileUp", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.ImgFileUpRequestBody Body;
        
        public ImgFileUpRequest() {
        }
        
        public ImgFileUpRequest(YRD.Web.SR.ImgFileUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class ImgFileUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rootpath;
        
        public ImgFileUpRequestBody() {
        }
        
        public ImgFileUpRequestBody(string strkey, byte[] data, string filename, string rootpath) {
            this.strkey = strkey;
            this.data = data;
            this.filename = filename;
            this.rootpath = rootpath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImgFileUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImgFileUpResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.ImgFileUpResponseBody Body;
        
        public ImgFileUpResponse() {
        }
        
        public ImgFileUpResponse(YRD.Web.SR.ImgFileUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class ImgFileUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ImgFileUpResult;
        
        public ImgFileUpResponseBody() {
        }
        
        public ImgFileUpResponseBody(bool ImgFileUpResult) {
            this.ImgFileUpResult = ImgFileUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesUpload_ThumbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesUpload_Thumb", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesUpload_ThumbRequestBody Body;
        
        public FilesUpload_ThumbRequest() {
        }
        
        public FilesUpload_ThumbRequest(YRD.Web.SR.FilesUpload_ThumbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesUpload_ThumbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rootpath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string thumbpath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public YRD.Web.SR.ArrayOfInt thumbsize;
        
        public FilesUpload_ThumbRequestBody() {
        }
        
        public FilesUpload_ThumbRequestBody(string strkey, byte[] data, string filename, string rootpath, string thumbpath, YRD.Web.SR.ArrayOfInt thumbsize) {
            this.strkey = strkey;
            this.data = data;
            this.filename = filename;
            this.rootpath = rootpath;
            this.thumbpath = thumbpath;
            this.thumbsize = thumbsize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesUpload_ThumbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesUpload_ThumbResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesUpload_ThumbResponseBody Body;
        
        public FilesUpload_ThumbResponse() {
        }
        
        public FilesUpload_ThumbResponse(YRD.Web.SR.FilesUpload_ThumbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesUpload_ThumbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilesUpload_ThumbResult;
        
        public FilesUpload_ThumbResponseBody() {
        }
        
        public FilesUpload_ThumbResponseBody(bool FilesUpload_ThumbResult) {
            this.FilesUpload_ThumbResult = FilesUpload_ThumbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesDelete", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesDeleteRequestBody Body;
        
        public FilesDeleteRequest() {
        }
        
        public FilesDeleteRequest(YRD.Web.SR.FilesDeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesDeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rootpath;
        
        public FilesDeleteRequestBody() {
        }
        
        public FilesDeleteRequestBody(string strkey, string filename, string rootpath) {
            this.strkey = strkey;
            this.filename = filename;
            this.rootpath = rootpath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesDeleteResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesDeleteResponseBody Body;
        
        public FilesDeleteResponse() {
        }
        
        public FilesDeleteResponse(YRD.Web.SR.FilesDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesDeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilesDeleteResult;
        
        public FilesDeleteResponseBody() {
        }
        
        public FilesDeleteResponseBody(bool FilesDeleteResult) {
            this.FilesDeleteResult = FilesDeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesDeleteByPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesDeleteByPath", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesDeleteByPathRequestBody Body;
        
        public FilesDeleteByPathRequest() {
        }
        
        public FilesDeleteByPathRequest(YRD.Web.SR.FilesDeleteByPathRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesDeleteByPathRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rootpath;
        
        public FilesDeleteByPathRequestBody() {
        }
        
        public FilesDeleteByPathRequestBody(string strkey, string rootpath) {
            this.strkey = strkey;
            this.rootpath = rootpath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesDeleteByPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesDeleteByPathResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesDeleteByPathResponseBody Body;
        
        public FilesDeleteByPathResponse() {
        }
        
        public FilesDeleteByPathResponse(YRD.Web.SR.FilesDeleteByPathResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesDeleteByPathResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilesDeleteByPathResult;
        
        public FilesDeleteByPathResponseBody() {
        }
        
        public FilesDeleteByPathResponseBody(bool FilesDeleteByPathResult) {
            this.FilesDeleteByPathResult = FilesDeleteByPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesDeleteByPathsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesDeleteByPaths", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesDeleteByPathsRequestBody Body;
        
        public FilesDeleteByPathsRequest() {
        }
        
        public FilesDeleteByPathsRequest(YRD.Web.SR.FilesDeleteByPathsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesDeleteByPathsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rootpath;
        
        public FilesDeleteByPathsRequestBody() {
        }
        
        public FilesDeleteByPathsRequestBody(string strkey, string rootpath) {
            this.strkey = strkey;
            this.rootpath = rootpath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesDeleteByPathsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesDeleteByPathsResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesDeleteByPathsResponseBody Body;
        
        public FilesDeleteByPathsResponse() {
        }
        
        public FilesDeleteByPathsResponse(YRD.Web.SR.FilesDeleteByPathsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesDeleteByPathsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilesDeleteByPathsResult;
        
        public FilesDeleteByPathsResponseBody() {
        }
        
        public FilesDeleteByPathsResponseBody(bool FilesDeleteByPathsResult) {
            this.FilesDeleteByPathsResult = FilesDeleteByPathsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesExist", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesExistRequestBody Body;
        
        public FilesExistRequest() {
        }
        
        public FilesExistRequest(YRD.Web.SR.FilesExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rootpath;
        
        public FilesExistRequestBody() {
        }
        
        public FilesExistRequestBody(string strkey, string filename, string rootpath) {
            this.strkey = strkey;
            this.filename = filename;
            this.rootpath = rootpath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilesExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilesExistResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.FilesExistResponseBody Body;
        
        public FilesExistResponse() {
        }
        
        public FilesExistResponse(YRD.Web.SR.FilesExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class FilesExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilesExistResult;
        
        public FilesExistResponseBody() {
        }
        
        public FilesExistResponseBody(bool FilesExistResult) {
            this.FilesExistResult = FilesExistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageSizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImageSize", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.GetImageSizeRequestBody Body;
        
        public GetImageSizeRequest() {
        }
        
        public GetImageSizeRequest(YRD.Web.SR.GetImageSizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class GetImageSizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rootpath;
        
        public GetImageSizeRequestBody() {
        }
        
        public GetImageSizeRequestBody(string strkey, string filename, string rootpath) {
            this.strkey = strkey;
            this.filename = filename;
            this.rootpath = rootpath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageSizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImageSizeResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.GetImageSizeResponseBody Body;
        
        public GetImageSizeResponse() {
        }
        
        public GetImageSizeResponse(YRD.Web.SR.GetImageSizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class GetImageSizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YRD.Web.SR.ArrayOfInt GetImageSizeResult;
        
        public GetImageSizeResponseBody() {
        }
        
        public GetImageSizeResponseBody(YRD.Web.SR.ArrayOfInt GetImageSizeResult) {
            this.GetImageSizeResult = GetImageSizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZipFileFromDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZipFileFromDirectory", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.ZipFileFromDirectoryRequestBody Body;
        
        public ZipFileFromDirectoryRequest() {
        }
        
        public ZipFileFromDirectoryRequest(YRD.Web.SR.ZipFileFromDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class ZipFileFromDirectoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rootpath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string targetpath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int compressLevel;
        
        public ZipFileFromDirectoryRequestBody() {
        }
        
        public ZipFileFromDirectoryRequestBody(string rootpath, string targetpath, string filename, int compressLevel) {
            this.rootpath = rootpath;
            this.targetpath = targetpath;
            this.filename = filename;
            this.compressLevel = compressLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZipFileFromDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZipFileFromDirectoryResponse", Namespace="http://www.yrd.com/", Order=0)]
        public YRD.Web.SR.ZipFileFromDirectoryResponseBody Body;
        
        public ZipFileFromDirectoryResponse() {
        }
        
        public ZipFileFromDirectoryResponse(YRD.Web.SR.ZipFileFromDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.yrd.com/")]
    public partial class ZipFileFromDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ZipFileFromDirectoryResult;
        
        public ZipFileFromDirectoryResponseBody() {
        }
        
        public ZipFileFromDirectoryResponseBody(bool ZipFileFromDirectoryResult) {
            this.ZipFileFromDirectoryResult = ZipFileFromDirectoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilesWebServiceSoapChannel : YRD.Web.SR.FilesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilesWebServiceSoapClient : System.ServiceModel.ClientBase<YRD.Web.SR.FilesWebServiceSoap>, YRD.Web.SR.FilesWebServiceSoap {
        
        public FilesWebServiceSoapClient() {
        }
        
        public FilesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.ImgFilesUpResponse YRD.Web.SR.FilesWebServiceSoap.ImgFilesUp(YRD.Web.SR.ImgFilesUpRequest request) {
            return base.Channel.ImgFilesUp(request);
        }
        
        public bool ImgFilesUp(string strkey, byte[] data, string filename, string rootpath, string ThumbPath, int width, int height) {
            YRD.Web.SR.ImgFilesUpRequest inValue = new YRD.Web.SR.ImgFilesUpRequest();
            inValue.Body = new YRD.Web.SR.ImgFilesUpRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            inValue.Body.ThumbPath = ThumbPath;
            inValue.Body.width = width;
            inValue.Body.height = height;
            YRD.Web.SR.ImgFilesUpResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).ImgFilesUp(inValue);
            return retVal.Body.ImgFilesUpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.ImgFilesUpResponse> YRD.Web.SR.FilesWebServiceSoap.ImgFilesUpAsync(YRD.Web.SR.ImgFilesUpRequest request) {
            return base.Channel.ImgFilesUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.ImgFilesUpResponse> ImgFilesUpAsync(string strkey, byte[] data, string filename, string rootpath, string ThumbPath, int width, int height) {
            YRD.Web.SR.ImgFilesUpRequest inValue = new YRD.Web.SR.ImgFilesUpRequest();
            inValue.Body = new YRD.Web.SR.ImgFilesUpRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            inValue.Body.ThumbPath = ThumbPath;
            inValue.Body.width = width;
            inValue.Body.height = height;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).ImgFilesUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.ImgFileUpResponse YRD.Web.SR.FilesWebServiceSoap.ImgFileUp(YRD.Web.SR.ImgFileUpRequest request) {
            return base.Channel.ImgFileUp(request);
        }
        
        public bool ImgFileUp(string strkey, byte[] data, string filename, string rootpath) {
            YRD.Web.SR.ImgFileUpRequest inValue = new YRD.Web.SR.ImgFileUpRequest();
            inValue.Body = new YRD.Web.SR.ImgFileUpRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            YRD.Web.SR.ImgFileUpResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).ImgFileUp(inValue);
            return retVal.Body.ImgFileUpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.ImgFileUpResponse> YRD.Web.SR.FilesWebServiceSoap.ImgFileUpAsync(YRD.Web.SR.ImgFileUpRequest request) {
            return base.Channel.ImgFileUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.ImgFileUpResponse> ImgFileUpAsync(string strkey, byte[] data, string filename, string rootpath) {
            YRD.Web.SR.ImgFileUpRequest inValue = new YRD.Web.SR.ImgFileUpRequest();
            inValue.Body = new YRD.Web.SR.ImgFileUpRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).ImgFileUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.FilesUpload_ThumbResponse YRD.Web.SR.FilesWebServiceSoap.FilesUpload_Thumb(YRD.Web.SR.FilesUpload_ThumbRequest request) {
            return base.Channel.FilesUpload_Thumb(request);
        }
        
        public bool FilesUpload_Thumb(string strkey, byte[] data, string filename, string rootpath, string thumbpath, YRD.Web.SR.ArrayOfInt thumbsize) {
            YRD.Web.SR.FilesUpload_ThumbRequest inValue = new YRD.Web.SR.FilesUpload_ThumbRequest();
            inValue.Body = new YRD.Web.SR.FilesUpload_ThumbRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            inValue.Body.thumbpath = thumbpath;
            inValue.Body.thumbsize = thumbsize;
            YRD.Web.SR.FilesUpload_ThumbResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesUpload_Thumb(inValue);
            return retVal.Body.FilesUpload_ThumbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesUpload_ThumbResponse> YRD.Web.SR.FilesWebServiceSoap.FilesUpload_ThumbAsync(YRD.Web.SR.FilesUpload_ThumbRequest request) {
            return base.Channel.FilesUpload_ThumbAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.FilesUpload_ThumbResponse> FilesUpload_ThumbAsync(string strkey, byte[] data, string filename, string rootpath, string thumbpath, YRD.Web.SR.ArrayOfInt thumbsize) {
            YRD.Web.SR.FilesUpload_ThumbRequest inValue = new YRD.Web.SR.FilesUpload_ThumbRequest();
            inValue.Body = new YRD.Web.SR.FilesUpload_ThumbRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            inValue.Body.thumbpath = thumbpath;
            inValue.Body.thumbsize = thumbsize;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesUpload_ThumbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.FilesDeleteResponse YRD.Web.SR.FilesWebServiceSoap.FilesDelete(YRD.Web.SR.FilesDeleteRequest request) {
            return base.Channel.FilesDelete(request);
        }
        
        public bool FilesDelete(string strkey, string filename, string rootpath) {
            YRD.Web.SR.FilesDeleteRequest inValue = new YRD.Web.SR.FilesDeleteRequest();
            inValue.Body = new YRD.Web.SR.FilesDeleteRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            YRD.Web.SR.FilesDeleteResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesDelete(inValue);
            return retVal.Body.FilesDeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteResponse> YRD.Web.SR.FilesWebServiceSoap.FilesDeleteAsync(YRD.Web.SR.FilesDeleteRequest request) {
            return base.Channel.FilesDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteResponse> FilesDeleteAsync(string strkey, string filename, string rootpath) {
            YRD.Web.SR.FilesDeleteRequest inValue = new YRD.Web.SR.FilesDeleteRequest();
            inValue.Body = new YRD.Web.SR.FilesDeleteRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.FilesDeleteByPathResponse YRD.Web.SR.FilesWebServiceSoap.FilesDeleteByPath(YRD.Web.SR.FilesDeleteByPathRequest request) {
            return base.Channel.FilesDeleteByPath(request);
        }
        
        public bool FilesDeleteByPath(string strkey, string rootpath) {
            YRD.Web.SR.FilesDeleteByPathRequest inValue = new YRD.Web.SR.FilesDeleteByPathRequest();
            inValue.Body = new YRD.Web.SR.FilesDeleteByPathRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.rootpath = rootpath;
            YRD.Web.SR.FilesDeleteByPathResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesDeleteByPath(inValue);
            return retVal.Body.FilesDeleteByPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteByPathResponse> YRD.Web.SR.FilesWebServiceSoap.FilesDeleteByPathAsync(YRD.Web.SR.FilesDeleteByPathRequest request) {
            return base.Channel.FilesDeleteByPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteByPathResponse> FilesDeleteByPathAsync(string strkey, string rootpath) {
            YRD.Web.SR.FilesDeleteByPathRequest inValue = new YRD.Web.SR.FilesDeleteByPathRequest();
            inValue.Body = new YRD.Web.SR.FilesDeleteByPathRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.rootpath = rootpath;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesDeleteByPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.FilesDeleteByPathsResponse YRD.Web.SR.FilesWebServiceSoap.FilesDeleteByPaths(YRD.Web.SR.FilesDeleteByPathsRequest request) {
            return base.Channel.FilesDeleteByPaths(request);
        }
        
        public bool FilesDeleteByPaths(string strkey, string rootpath) {
            YRD.Web.SR.FilesDeleteByPathsRequest inValue = new YRD.Web.SR.FilesDeleteByPathsRequest();
            inValue.Body = new YRD.Web.SR.FilesDeleteByPathsRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.rootpath = rootpath;
            YRD.Web.SR.FilesDeleteByPathsResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesDeleteByPaths(inValue);
            return retVal.Body.FilesDeleteByPathsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteByPathsResponse> YRD.Web.SR.FilesWebServiceSoap.FilesDeleteByPathsAsync(YRD.Web.SR.FilesDeleteByPathsRequest request) {
            return base.Channel.FilesDeleteByPathsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.FilesDeleteByPathsResponse> FilesDeleteByPathsAsync(string strkey, string rootpath) {
            YRD.Web.SR.FilesDeleteByPathsRequest inValue = new YRD.Web.SR.FilesDeleteByPathsRequest();
            inValue.Body = new YRD.Web.SR.FilesDeleteByPathsRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.rootpath = rootpath;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesDeleteByPathsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.FilesExistResponse YRD.Web.SR.FilesWebServiceSoap.FilesExist(YRD.Web.SR.FilesExistRequest request) {
            return base.Channel.FilesExist(request);
        }
        
        public bool FilesExist(string strkey, string filename, string rootpath) {
            YRD.Web.SR.FilesExistRequest inValue = new YRD.Web.SR.FilesExistRequest();
            inValue.Body = new YRD.Web.SR.FilesExistRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            YRD.Web.SR.FilesExistResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesExist(inValue);
            return retVal.Body.FilesExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.FilesExistResponse> YRD.Web.SR.FilesWebServiceSoap.FilesExistAsync(YRD.Web.SR.FilesExistRequest request) {
            return base.Channel.FilesExistAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.FilesExistResponse> FilesExistAsync(string strkey, string filename, string rootpath) {
            YRD.Web.SR.FilesExistRequest inValue = new YRD.Web.SR.FilesExistRequest();
            inValue.Body = new YRD.Web.SR.FilesExistRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).FilesExistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.GetImageSizeResponse YRD.Web.SR.FilesWebServiceSoap.GetImageSize(YRD.Web.SR.GetImageSizeRequest request) {
            return base.Channel.GetImageSize(request);
        }
        
        public YRD.Web.SR.ArrayOfInt GetImageSize(string strkey, string filename, string rootpath) {
            YRD.Web.SR.GetImageSizeRequest inValue = new YRD.Web.SR.GetImageSizeRequest();
            inValue.Body = new YRD.Web.SR.GetImageSizeRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            YRD.Web.SR.GetImageSizeResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).GetImageSize(inValue);
            return retVal.Body.GetImageSizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.GetImageSizeResponse> YRD.Web.SR.FilesWebServiceSoap.GetImageSizeAsync(YRD.Web.SR.GetImageSizeRequest request) {
            return base.Channel.GetImageSizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.GetImageSizeResponse> GetImageSizeAsync(string strkey, string filename, string rootpath) {
            YRD.Web.SR.GetImageSizeRequest inValue = new YRD.Web.SR.GetImageSizeRequest();
            inValue.Body = new YRD.Web.SR.GetImageSizeRequestBody();
            inValue.Body.strkey = strkey;
            inValue.Body.filename = filename;
            inValue.Body.rootpath = rootpath;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).GetImageSizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YRD.Web.SR.ZipFileFromDirectoryResponse YRD.Web.SR.FilesWebServiceSoap.ZipFileFromDirectory(YRD.Web.SR.ZipFileFromDirectoryRequest request) {
            return base.Channel.ZipFileFromDirectory(request);
        }
        
        public bool ZipFileFromDirectory(string rootpath, string targetpath, string filename, int compressLevel) {
            YRD.Web.SR.ZipFileFromDirectoryRequest inValue = new YRD.Web.SR.ZipFileFromDirectoryRequest();
            inValue.Body = new YRD.Web.SR.ZipFileFromDirectoryRequestBody();
            inValue.Body.rootpath = rootpath;
            inValue.Body.targetpath = targetpath;
            inValue.Body.filename = filename;
            inValue.Body.compressLevel = compressLevel;
            YRD.Web.SR.ZipFileFromDirectoryResponse retVal = ((YRD.Web.SR.FilesWebServiceSoap)(this)).ZipFileFromDirectory(inValue);
            return retVal.Body.ZipFileFromDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YRD.Web.SR.ZipFileFromDirectoryResponse> YRD.Web.SR.FilesWebServiceSoap.ZipFileFromDirectoryAsync(YRD.Web.SR.ZipFileFromDirectoryRequest request) {
            return base.Channel.ZipFileFromDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<YRD.Web.SR.ZipFileFromDirectoryResponse> ZipFileFromDirectoryAsync(string rootpath, string targetpath, string filename, int compressLevel) {
            YRD.Web.SR.ZipFileFromDirectoryRequest inValue = new YRD.Web.SR.ZipFileFromDirectoryRequest();
            inValue.Body = new YRD.Web.SR.ZipFileFromDirectoryRequestBody();
            inValue.Body.rootpath = rootpath;
            inValue.Body.targetpath = targetpath;
            inValue.Body.filename = filename;
            inValue.Body.compressLevel = compressLevel;
            return ((YRD.Web.SR.FilesWebServiceSoap)(this)).ZipFileFromDirectoryAsync(inValue);
        }
    }
}
