//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selcardrule_foodtype
    {
        /// <summary>
        /// 会员卡可消费菜品类型关系表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CardRuleID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FoodTypeID { get; set; }
        /// <summary>
        /// 绑定的金额类型（1主余额2副余额3次数）
        /// </summary>
        public int MoneyType { get; set; }
    }
}


