//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selcardoperationuser
    {
        /// <summary>
        /// 会员卡用户操作余额变化记录表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 人员ID
        /// </summary>
        public string UserID { get; set; }
        /// <summary>
        /// 卡ID
        /// </summary>
        public string CardID { get; set; }
        /// <summary>
        /// 操作类型（1绑定2消费3充值）
        /// </summary>
        public Nullable<int> Type { get; set; }
        /// <summary>
        /// 介绍
        /// </summary>
        public string Info { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 消费的店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 消费的金额或者次数
        /// </summary>
        public string ChangeMoney { get; set; }
        ///// <summary>
        ///// 消费的次数
        ///// </summary>
        //public Nullable<int> ChangeCount { get; set; }
        /// <summary>
        /// 商家操作人员ID
        /// </summary>
        public string SellerID { get; set; }
        /// <summary>
        /// 剩余金额
        /// </summary>
        public Nullable<decimal> SurplusMoney { get; set; }
        /// <summary>
        /// 剩余金额
        /// </summary>
        public Nullable<int> SurplusCount { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 订单ID
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 支付方式。
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 会员卡规则
        /// </summary>
        public string CardRuleName { get; set; }
        /// <summary>
        /// 剩余金额或者次数 主卡
        /// </summary>
        public decimal SurplusMoneyMain { get; set; }
        /// <summary>
        /// 剩余金额或者次数 副卡
        /// </summary>
        public decimal SurplusMoneyVice { get; set; }
        /// <summary>
        /// 消费的金额或者次数 主卡
        /// </summary>
        public decimal ChangeMoneyMain { get; set; }
        /// <summary>
        /// 消费的金额或者次数 副卡
        /// </summary>
        public decimal ChangeMoneyVice { get; set; }
        /// <summary>
        /// 实际金额
        /// </summary>
        public decimal TrueMoney { get; set; }
    }
}


