//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selcarddetail
    {


        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderNumber { get; set; }
        /// <summary>
        /// 1 开卡 2 充值 3消费
        /// </summary>
        public int Type { get; set; }
        /// <summary>
        /// 会员卡编号
        /// </summary>
        public string CardID { get; set; }
        /// <summary>
        /// 变化之前
        /// </summary>
        public decimal BeforeOriginAmount { get; set; }
        /// <summary>
        /// 变化标识 1 加钱 -1减钱
        /// </summary>
        public int SignOriginAmount { get; set; }
        /// <summary>
        /// 变化金额
        /// </summary>
        public decimal DataOriginAmount { get; set; }
        /// <summary>
        /// 变化之后
        /// </summary>
        public decimal AfterOriginAmount { get; set; }
        /// <summary>
        /// 变化之前
        /// </summary>
        public decimal BeforeExtendAmount { get; set; }
        /// <summary>
        /// 变化标识 1 加钱 -1减钱
        /// </summary>
        public int SignExtentAmount { get; set; }
        /// <summary>
        /// 变化金额
        /// </summary>
        public decimal DataExtendAmount { get; set; }
        /// <summary>
        /// 变化之后
        /// </summary>
        public decimal AfterExtendAmount { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 支付方式
        /// </summary>
        public int PayMode { get; set; }
        /// <summary>
        /// 工作人员ID（收银员）
        /// </summary>
        public string SellerID { get; set; }
        /// <summary>
        /// 短备注 不带结余
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 备注 带结余
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BatchId { get; set; }
    }
}


