//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class selcardaccount
    {
        /// <summary>
        /// 会员卡编号（16位长度）
        /// </summary>
        [Key]
        public string CardID { get; set; }
        /// <summary>
        /// 会员卡名称
        /// </summary>
        public string CardName { get; set; }
        /// <summary>
        /// 会员卡类型ID
        /// 
        /// </summary>
        public int CardTypeID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 所属用户ID
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 金额、次数
        /// </summary>
        public decimal OriginAmount { get; set; }
        /// <summary>
        /// 额外金额、次数、打折（0.95）
        /// </summary>
        public decimal ExtendAmount { get; set; }
        /// <summary>
        /// 操作时间
        /// </summary>
        public DateTime OperatorDateTime { get; set; }
        /// <summary>
        /// 会员卡开始时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 会员卡过期时间
        /// </summary>
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// 卡的状态（1可用 0不可用 2 锁定）
        /// </summary>
        public int CardState { get; set; }
        /// <summary>
        /// 卡上积分
        /// </summary>
        public int Score { get; set; }
    }
}


