//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class selcard
    {
        /// <summary>
        /// 会员卡编号（16位长度）
        /// </summary>
        [Key]
        public string CardID { get; set; }
        /// <summary>
        /// 会员卡类型ID
        /// </summary>
        public string CardTypeID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 所属用户ID
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 购卡金额
        /// </summary>
        public decimal StandAmount { get; set; }
        /// <summary>
        /// 金额、次数
        /// </summary>
        public decimal OriginAmount { get; set; }
        /// <summary>
        /// 额外金额、次数、打折（0.95）
        /// </summary>
        public decimal ExtendAmount { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 会员卡开始时间
        /// </summary>
        public Nullable<System.DateTime> StartTime { get; set; }
        /// <summary>
        /// 会员卡结束时间
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 时长（单位为年）
        /// </summary>
        public int Duration { get; set; }
        /// <summary>
        /// 卡的状态（1可用 0不可用 2 锁定）
        /// </summary>
        public int CardState { get; set; }
        /// <summary>
        /// 同一批的
        /// </summary>
        public string BatchID { get; set; }
        /// <summary>
        /// 介绍
        /// </summary>
        public string Info { get; set; }
        /// <summary>
        /// 是否连锁通用（1是0否）
        /// </summary>
        public Nullable<int> IsCurrency { get; set; }
        /// <summary>
        /// 会员卡规则ID
        /// </summary>
        public string CardRuleName { get; set; }
        /// <summary>
        /// 卡上积分
        /// </summary>
        public Nullable<int> Score { get; set; }
        /// <summary>
        /// 工作人员ID（收银员）
        /// </summary>
        public string SellerID { get; set; }
        /// <summary>
        /// 会员卡规则ID
        /// </summary>
        public string CardRuleId { get; set; }
    }
}


