//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class selcardrecharge
    {
        /// <summary>
        /// 编号
        /// </summary>
        public string ID { get; set; }

        public string CardID { get; set; }
        /// <summary>
        /// 会员卡类型ID
        /// </summary>
        public int CardTypeID { get; set; }
        /// <summary>
        /// 1开卡 2 充值
        /// </summary>
        public int RechargeType { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 所属用户ID
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 支付方式
        /// </summary>
        public int PayMode { get; set; }
        /// <summary>
        /// 购卡金额
        /// </summary>
        public decimal StandAmount { get; set; }
        /// <summary>
        /// 金额、次数
        /// </summary>
        public decimal OriginAmount { get; set; }
        /// <summary>
        /// 额外金额、次数、打折（0.95）
        /// </summary>
        public decimal ExtendAmount { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 会员卡开始时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 会员卡结束时间
        /// </summary>
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// 时长（单位为年）
        /// </summary>
        public int Duration { get; set; }

        /// <summary>
        /// 会员卡规则ID
        /// </summary>
        public string CardRuleId { get; set; }
        /// <summary>
        /// 会员卡规则ID
        /// </summary>
        public string CardRuleName { get; set; }
        /// <summary>
        /// 工作人员ID（收银员）
        /// </summary>
        public string SellerID { get; set; }
        /// <summary>
        /// 批处理编号 同一次操作的编号
        /// </summary>
        public string BatchId { get; set; }
    }
}


