//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selfoodspecifications
    {
        /// <summary>
        /// 菜品规格表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 规格图片
        /// </summary>
        public string ImgUrl { get; set; }
        /// <summary>
        /// 菜品ID
        /// </summary>
        public string FoodID { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; } 
        /// <summary>
        /// 普通价格
        /// </summary>
        public decimal PriceGeneral { get; set; }
        /// <summary>
        /// 会员价格
        /// </summary>
        public decimal PriceVip { get; set; }

        /// <summary>
        /// 外卖价
        /// </summary>
        public decimal PriceTakeOut { get; set; }

        /// <summary>
        /// 特价类型（1按周2按月）
        /// </summary>
        public int TimeType { get; set; }

        /// <summary>
        /// 特价价格
        /// </summary>
        public decimal PriceSpecial { get; set; }

        public string DayValue { get; set; }

    }
}


