//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selfood_manager
    {
        /// <summary>
        /// 商家菜品厨师关系表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 商家菜品ID
        /// </summary>
        public string FoodID { get; set; }
        /// <summary>
        /// 商家用户ID
        /// </summary>
        public string ManagerID { get; set; }
    }
}


