//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selfood
    {
        /// <summary>
        /// 店铺菜品表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 菜名称
        /// </summary>
        public string FoodName { get; set; }
        /// <summary>
        /// 主料
        /// </summary>
        public string MainIngredient { get; set; }
        /// <summary>
        /// 辅料
        /// </summary>
        public string Accessories { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 菜品类别表
        /// </summary>
        public string FoodTypeID { get; set; }
        /// <summary>
        /// 列表图Url
        /// </summary>
        public string ListImgUrl { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 创建者ID
        /// </summary>
        public string CreateSellerID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }

        /// <summary>
        /// 默认数量
        /// </summary>
        public int DefaultCount { get; set; }
        /// <summary>
        /// 剩余库存数量
        /// </summary>
        public int RemainCount { get; set; }
        /// <summary>
        /// 菜品单位ID
        /// </summary>
        public string FoodUnitID { get; set; }
        /// <summary>
        /// 制作时间（分钟）
        /// </summary>
        public int MakeMinute { get; set; }

        /// <summary>
        /// 打印机id
        /// </summary>
        public string PrintID { get; set; }

        /// <summary>
        /// 是否有多个规格(1是0否)
        /// </summary>
        //public int IsHavePecification { get; set; }
        /// <summary>
        /// 0 半成品 1 成品
        /// </summary>
        public int FinishType { get; set; }
        /// <summary>
        /// 0 无 1 有
        /// </summary>
        public int IsTeJia { get; set; }
        /// <summary>
        /// 0 无 1 有
        /// </summary>
        public int IsPrint { get; set; }

        /// <summary>
        /// 是否可用（0不可用 即下架状态 1可用 ）
        /// </summary>
        public bool IsAvailable { get; set; }

    }
}


