//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selfoodspecialtime
    {
        /// <summary>
        /// 商家菜品特价时间表
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 特价图片
        /// </summary>
        public string ImgUrl { get; set; }
        /// <summary>
        /// 菜品ID
        /// </summary>
        public string FoodID { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public Nullable<int> Sort { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public Nullable<int> IsDel { get; set; }
        /// <summary>
        /// 特价类型（1按周天2按月天）
        /// </summary>
        public Nullable<int> Type { get; set; }
        /// <summary>
        /// 普通价格
        /// </summary>
        public Nullable<decimal> PriceGeneral { get; set; }
        /// <summary>
        /// 会员价格
        /// </summary>
        public Nullable<decimal> PriceVip { get; set; }
        /// <summary>
        /// 特价价格
        /// </summary>
        public Nullable<decimal> PriceSpecial { get; set; }
        /// <summary>
        /// 天数
        /// </summary>
        public string DayValue { get; set; }
    }
}


