//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class sellogshopmoney
    {
        /// <summary>
        /// 店铺余额变化表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 变化类型（1收入2支出）
        /// </summary>
        public int ChangeType { get; set; }
        /// <summary>
        /// 变化金额
        /// </summary>
        public decimal ChangeMoney { get; set; }
        /// <summary>
        /// 变化名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public System.DateTime CreateDate { get; set; }

        /// <summary>
        /// 订单ID
        /// </summary>
        public string OrderID { get; set; }

        /// <summary>
        /// 餐桌ID
        /// </summary>
        public string TableID { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary> 
        public string UserID { get; set; }

        public string UserName { get; set; } 
    }
}


