//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selpackage
    {
        /// <summary>
        /// 店铺套餐表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 套餐名
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 列表图片
        /// </summary>
        public string ListImgUrl { get; set; }  
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; } 
        /// <summary>
        /// 创建者ID
        /// </summary>
        public string CreateSellerID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 打印机ID
        /// </summary>
        public string PrintID { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        public System.DateTime EndTime { get; set; }
        public string Introduction { get; set; }
        public decimal Price { get; set; }

        /// <summary>
        /// 是否自助 0否 1是
        /// </summary>
        public bool IsSelfHelp { get; set; }

        /// <summary>
        /// 使用次数（计次卡专用）
        /// </summary>
        public int UsageCount { get; set; }

        /// <summary>
        /// 菜品类型ID
        /// </summary>
        public string FoodTypeID { get; set; }
        /// <summary>
        /// 是否可用（0不可用 即下架状态 1可用 ）
        /// </summary>
        public bool IsAvailable { get; set; }
    }
}


