//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selpackage_food
    {
        /// <summary>
        /// 店铺套餐菜品关系表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 店铺套餐ID
        /// </summary>
        public string PackageID { get; set; }
        /// <summary>
        /// 菜品ID
        /// </summary>
        public string FoodID { get; set; }

        /// <summary>
        /// 规格ID
        /// </summary>
        public string FoodSpecificationsID { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        public int CountNum { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
    }
}


