//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selrole
    {
        /// <summary>
        /// 商家角色表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 角色名
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public Nullable<int> Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public int IsAvailable { get; set; }
        /// <summary>
        /// 创建管理员ID
        /// </summary>
        public string CreateManagerID { get; set; }
        /// <summary>
        /// 商家ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 是否可以删除（1是0否）
        /// </summary>
        public int IsDefault { get; set; }
    }
}


