//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selroom
    {
        /// <summary>
        /// 店铺房间表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 房间名称
        /// </summary>
        public string RoomName { get; set; } 
        /// <summary>
        /// 面积
        /// </summary>
        public decimal Acreage { get; set; }
        /// <summary>
        /// 店铺房间表ID
        /// </summary>
        public string DepartmentID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 创建者ID
        /// </summary>
        public string CreateSellerID { get; set; }

    }
}


