//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selshop
    {
        /// <summary>
        /// 商家店铺ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 店铺名称
        /// </summary>
        public string ShopName { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 地图经度
        /// </summary>
        public Nullable<double> MapLng { get; set; }
        /// <summary>
        /// 地图维度
        /// </summary>
        public Nullable<double> MapLat { get; set; }
        /// <summary>
        /// 删除状态
        /// </summary>
        public Nullable<int> IsDel { get; set; }
        /// <summary>
        /// 锁定状态
        /// </summary>
        public Nullable<int> IsLock { get; set; }
        /// <summary>
        /// 联系人
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 手机
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string Tel { get; set; }
        /// <summary>
        /// qq
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 省ID
        /// </summary>
        public string ProvinceID { get; set; }
        /// <summary>
        /// 市ID
        /// </summary>
        public string CityID { get; set; }
        /// <summary>
        /// 县区ID
        /// </summary>
        public string CountyID { get; set; }
        /// <summary>
        /// 商圈ID
        /// </summary>
        public string AreaID { get; set; }
        /// <summary>
        /// 详细地址
        /// </summary>
        public string AddressInfo { get; set; }
        /// <summary>
        /// 管理区域类型（1全国2省3市4县区5商圈，其他无）
        /// </summary>
        public string ManagerAreaType { get; set; }
        /// <summary>
        /// 创建管理员ID
        /// </summary>
        public string CreateManagerID { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 审核通过开通时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 使用结束时间
        /// </summary>
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// 商家规模ID
        /// </summary>
        public string ScaleID { get; set; }
        /// <summary>
        /// 商家性质ID（1独立2直营3加盟）
        /// </summary>
        public string PropertyID { get; set; }
        /// <summary>
        /// 拥有者SellerID
        /// </summary>
        public string OwnSellerID { get; set; }

        /// <summary>
        /// 代理公司ID
        /// </summary>
        public string ProxyCompanyID { get; set; }
        /// <summary>
        /// 列表缩略图
        /// </summary>
        public string ListImg { get; set; }
        /// <summary>
        /// 品牌标识名称
        /// </summary> 
        public string BrandName { get; set; }

        /// <summary>
        /// 品牌标识
        /// </summary> 
        public string BrandLogo { get; set; }
        /// <summary>
        /// 店铺类型ID(火锅，炒菜)
        /// </summary>
        public string ShopTypeID { get; set; }
        /// <summary>
        /// 午餐开始营业时间
        /// </summary>
        public string BusinessTimeStartLunch { get; set; }
        /// <summary>
        /// 午餐结束营业时间
        /// </summary>
        public string BusinessTimeEndLunch { get; set; }
        /// <summary>
        /// 晚餐开始营业时间
        /// </summary>
        public string BusinessTimeStartDinner { get; set; }
        /// <summary>
        /// 晚餐结束营业时间
        /// </summary>
        public string BusinessTimeEndDinner { get; set; }
        /// <summary>
        /// 是否可以预定（1是0否）
        /// </summary>
        public Nullable<int> IsCanReserve { get; set; }
        /// <summary>
        /// 店铺等级 
        /// </summary>
        public int VersionID { get; set; }
        /// <summary>
        /// 库存版本编号
        /// </summary>
        public int StockVersionID { get; set; }
        /// <summary>
        /// 关联key连锁店用（guid）
        /// </summary>
        public string LinkKey { get; set; }
        /// <summary>
        /// 店铺最低极限余额
        /// </summary>
        public Nullable<decimal> ShopLimitMoney { get; set; }
        /// <summary>
        /// 预定联系手机号
        /// </summary>
        public string ReservePhone { get; set; }
        /// <summary>
        /// 支付宝账户
        /// </summary>
        public string BankAlipay { get; set; }
        /// <summary>
        /// 微信账户
        /// </summary>
        public string BankWeiXin { get; set; }
        /// <summary>
        /// 支付宝账户扫码图
        /// </summary>
        public string BankAlipayImg { get; set; }
        /// <summary>
        /// 微信账户扫码图
        /// </summary>
        public string BankWeiXinImg { get; set; }
        /// <summary>
        /// 短信积分变更提醒
        /// </summary>
        public Nullable<int> SmsIntegralChange { get; set; }
        /// <summary>
        /// 短信密码变更提醒
        /// </summary>
        public Nullable<int> SmsPasswordChange { get; set; }
        /// <summary>
        /// 加菜打印规则(0不打印1按单品2按订单）
        /// </summary>
        public Nullable<int> AddFoodPrintRule { get; set; }
        /// <summary>
        /// 传菜打印规则(0不打印1按单品2按订单）
        /// </summary>
        public Nullable<int> PassFoodPrintRule { get; set; }
        /// <summary>
        /// 传菜打印机ID
        /// </summary>
        public string PassFoodPrintID { get; set; }
        /// <summary>
        /// 是否消费送积分(1是0否)
        /// </summary>
        public Nullable<int> IsConsumptionAddIntegral { get; set; }
        /// <summary>
        /// 消费一元送多少积分
        /// </summary>
        public Nullable<int> ConsumptionAddIntegral { get; set; }
        /// <summary>
        /// 是否充值送积分(1是0否)
        /// </summary>
        public Nullable<int> IsRechargeAddIntegral { get; set; }
        /// <summary>
        /// 充值一元送多少积分
        /// </summary>
        public Nullable<int> RechargeAddIntegral { get; set; }
        /// <summary>
        /// 是否开启分销（1是0否）
        /// </summary>
        public Nullable<int> IsDistribution { get; set; }
        /// <summary>
        /// 商家分销返利点数（例如百分之一填0.01）
        /// </summary>
        public Nullable<float> Percentage { get; set; }
        /// <summary>
        /// 最后一次设置返利的时间
        /// </summary>
        public Nullable<System.DateTime> SetRebateTime { get; set; }
        /// <summary>
        /// 审核通过的时间
        /// </summary>
        public Nullable<System.DateTime> AuditTime { get; set; }
        /// <summary>
        /// 0 待审核 1审核通过 2审核失败
        /// </summary>
        public int AuditStatus { get; set; }
        /// <summary>
        /// 收银台最大个数(默认1)
        /// </summary>
        public Nullable<int> CashierMaxCount { get; set; }
        /// <summary>
        /// 语音播放编号
        /// </summary>
        public string VoiceId { get; set; }
    }
}


