//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selshopsmsset
    {
        /// <summary>
        /// 商家店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 短信生日接受
        /// </summary>
        public int SmsBirthdayAccept { get; set; }
        /// <summary>
        /// 前几天
        /// </summary>
        public int Day { get; set; }
        /// <summary>
        /// 小时
        /// </summary>
        public int Hour { get; set; }
        /// <summary>
        /// 分钟
        /// </summary>
        public int Minute { get; set; }
        /// <summary>
        /// 短信商家接受
        /// </summary>
        public int SmsShopAccept { get; set; }
        /// <summary>
        /// SmsUserAccept
        /// </summary>
        public int SmsUserAccept { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime OperatorDateTime { get; set; }
    }
}


