//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selshopdistributionopendetail
    {
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 商家店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 是否开启（0未开启 1开启）
        /// </summary>
        public bool IsOpen { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 是否自动操作
        /// </summary>
        public bool IsAuto { get; set; }
        /// <summary>
        /// 操作人员编号
        /// </summary>
        public string ManagerId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    }
}


