//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class selshopvoice
    {
        /// <summary>
        /// 催菜语音
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 语音编号
        /// </summary>
        public string VoiceId { get; set; }
        /// <summary>
        /// 语音消息
        /// </summary>
        public string VoiceMessage { get; set; }

        public DateTime CreateTime { get; set; }

    }
}


