//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selshopjinbirecharge
    {
        /// <summary>
        /// 充值编号
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 用户编号
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ManagerID { get; set; }
        /// <summary>
        /// 充值金额
        /// </summary>
        public decimal Data { get; set; }
        /// <summary>
        /// 充值时间
        /// </summary>
        public System.DateTime DT { get; set; }
        /// <summary>
        /// 充值类型  0 提交充值 1充值成功
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// 2 支付宝 3 微信
        /// </summary>
        public int Mode { get; set; }
        /// <summary>
        /// 充值来源 0 pc
        /// </summary>
        public int Origin { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public bool IsAvailable { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BatchId { get; set; }
        /// <summary>
        /// 充值到账时间
        /// </summary>
        public Nullable<System.DateTime> ConfirmDT { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Contents { get; set; }
    }
}


