//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selshopdistribution
    {
        /// <summary>
        /// 商家店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 是否签署分销协议（1是0否）
        /// </summary>
        public bool IsSignAgreement { get; set; }

        public Nullable<DateTime> SignAgreementTime { get; set; }
        /// <summary>
        /// 分销比例
        /// </summary>
        public decimal Percentage { get; set; }
        /// <summary>
        /// 最后一次设置分销比例的时间
        /// </summary>
        public System.DateTime SetPercentageTime { get; set; }

        public bool IsSetPercentage { get; set; }
        /// <summary>
        /// 是否开启（0未开启 1开启）
        /// </summary>
        public bool IsOpen { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime OperatorDateTime { get; set; }
    }
}


