//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selshopopen
    {
        /// <summary>
        /// 店铺开通编号ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 充值时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 购买月份
        /// </summary>
        public int Month { get; set; }
        /// <summary>
        /// 额外月份
        /// </summary>
        public int ExMonth { get; set; }
        /// <summary>
        /// 金额
        /// </summary>
        public decimal Money { get; set; } 
        /// <summary>
        /// 开通时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 到期时间
        /// </summary>
        public System.DateTime EndTime { get; set; } 
        /// <summary>
        /// 充值来源（1支付宝2微信）
        /// </summary>
        public int PayType { get; set; }
        /// <summary>
        /// 版本编号
        /// </summary> 
        public string VersionID { get; set; }
        /// <summary>
        /// 0 提交成功  1 回调成功
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// 回调成功
        /// </summary>
        public Nullable<System.DateTime> SuccessTime { get; set; }

        /// <summary>
        /// 0 未删除 1已删除
        /// </summary>
        public int IsDel { get; set; }

        public string Remark { get; set; }
    }
}


