//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selshopjinbidetail
    {
        /// <summary>
        /// 
        /// </summary>
        public string OrderNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime DT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Sign { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool IsAuto { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal Before { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal Data { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal After { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BatchId { get; set; }
    }
}


