//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class selshopjinbiaccount
    {
        /// <summary>
        /// 商家店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal Jinbi { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime OperatorDateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime RowVersion { get; set; }
    }
}


