//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class seltable
    {
        /// <summary>
        /// 店铺餐桌表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 餐桌名
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 餐桌字母
        /// </summary>
        public string TableLetter { get; set; }
        /// <summary>
        /// 餐桌数字编号
        /// </summary>
        public int TableNum { get; set; }
        /// <summary>
        /// 最大人数
        /// </summary>
        public int MaxPeople { get; set; }
        /// <summary>
        /// 最低消费
        /// </summary>
        public decimal MinConsumption { get; set; }  
        public string RoomID { get; set; }
        /// <summary>
        /// 所属店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public  int Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// 二维码图片地址
        /// </summary>
        public string TwoDimensionCodeUrl { get; set; }
        /// <summary>
        /// 仓库ID
        /// </summary>
        public string WareHouseID { get; set; }
        /// <summary>
        /// 打印机ID
        /// </summary>
        public string PrintID { get; set; }
    }
}


