//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class seltablestate
    {
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 店铺餐桌表ID
        /// </summary>
        public string TableID { get; set; }
        /// <summary>
        /// 商家编号
        /// </summary>

        public string ShopID { get; set; }
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 餐桌状态(1空闲2正在使用3已预订4维护中5其他状态)
        /// </summary>
        public int TableState { get; set; }
        /// <summary>
        /// 订单来源(如果是开台就记录的开台的订单，如果开台时没订单就先记录一个空订单，等确认下单的时候，再补上，预定就记录的预定的订单，维护没有对应订单)
        /// </summary>
        public string OrderOrigin { get; set; }
        /// <summary>
        /// 备注(备注说明一下餐桌需要备注的地方)
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 是否有效 0无效1有效
        /// </summary>
        public bool IsAvailable { get; set; }
        /// <summary>
        /// 预定金额
        /// </summary>
        public decimal Money { get; set; }
        /// <summary>
        /// 预定电话
        /// </summary>
        public string ReservePhone { get; set; }
        /// <summary>
        /// 预定时间
        /// </summary>
        public Nullable<System.DateTime> ReserveTime { get; set; }
        /// <summary>
        /// 折后金额
        /// </summary>
        public decimal DiscountPrice { get; set; }
    }
}


