//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysbase
    {
        /// <summary>
        /// 平台基本参数ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 平台名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 平台地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Tel { get; set; }
        /// <summary>
        /// 平台LOGO
        /// </summary>
        public string ICON { get; set; }
        /// <summary>
        /// 平台总金额
        /// </summary>
        public Nullable<decimal> TotalMoney { get; set; }
    }
}


