//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysfunctiontype
    {
        /// <summary>
        /// 平台功能类型表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 版本类型名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 类型(1免费版2微店版3聚餐版4宴会版5库存6三级分销)
        /// </summary>
        public Nullable<int> Type { get; set; }
        /// <summary>
        /// 功能类型表ID
        /// </summary>
        public Nullable<int> Sort { get; set; }
        /// <summary>
        /// 价格
        /// </summary>
        public Nullable<decimal> Price { get; set; }
    }
}


