//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class syslogmanageroperate
    {
        /// <summary>
        /// 管理员一般操作记录表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 管理员ID
        /// </summary>
        public string ManagerID { get; set; }
        /// <summary>
        /// 日志详情
        /// </summary>
        public string Contents { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 操作类型（1增加2删除3修改4登陆5锁定6审核7其他）
        /// </summary>
        public Nullable<int> Type { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}


