//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmanager
    {
        /// <summary>
        /// 管理员ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 登录名
        /// </summary>
        public string LoginName { get; set; }
        /// <summary>
        /// 登陆密码
        /// </summary>
        public string LoginPwd { get; set; }
        /// <summary>
        /// 是否删除状态(1是0否)
        /// </summary>
        public Nullable<int> IsDel { get; set; }
        /// <summary>
        /// 是否锁定状态（1是0否）
        /// </summary>
        public Nullable<int> IsLock { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string HeadImgUrl { get; set; }
        /// <summary>
        /// 昵称
        /// </summary>
        public string NickName { get; set; }
        /// <summary>
        /// 入职时间
        /// </summary>
        public Nullable<System.DateTime> Hiredate { get; set; }
        /// <summary>
        /// 员工编号
        /// </summary>
        public string ManagerNo { get; set; }
        /// <summary>
        /// 手机
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 性别（1男0女）
        /// </summary>
        public Nullable<int> Gender { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public Nullable<System.DateTime> Birthday { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}


