//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmanager_role
    {
        /// <summary>
        /// 关系（系统管理员-系统角色）ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 系统角色ID
        /// </summary>
        public string SysRoleID { get; set; }
        /// <summary>
        /// 系统管理员ID
        /// </summary>
        public string SysManagerID { get; set; }
    }
}


