//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysnoticesend
    {
        /// <summary>
        /// 消息发送表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public string Contents { get; set; }
        /// <summary>
        /// 发送时间
        /// </summary>
        public Nullable<System.DateTime> SendTime { get; set; }
        /// <summary>
        /// 发送人ID
        /// </summary>
        public string SendManager_ID { get; set; }
        /// <summary>
        /// 接收人ID(多人用逗号隔开)ID供查看给发送给谁
        /// </summary>
        public string ReceiveUsersID { get; set; }
        /// <summary>
        /// 接收人名字列表（只存储名字方便发件人查看）
        /// </summary>
        public string ReceiveUsersName { get; set; }
        /// <summary>
        /// 发送人删除状态(1.已删除.0未删除) 软删除
        /// </summary>
        public Nullable<int> IsDel { get; set; }
        /// <summary>
        /// 接收者用户类型 （1管理员2代理3商家4用户）
        /// </summary>
        public Nullable<int> ReUserType { get; set; }
        /// <summary>
        /// 接收者用户类型详情加用户ID 例如（1-25）
        /// </summary>
        public string ReUserTypeInfo { get; set; }
        /// <summary>
        /// 发送状态（1已发送0未发送）
        /// </summary>
        public Nullable<int> SendState { get; set; }
        /// <summary>
        /// 发送人名称
        /// </summary>
        public string SenderName { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 发送类型(0系统通知1交易通知)
        /// </summary>
        public Nullable<int> SendType { get; set; }
        /// <summary>
        /// 省ID
        /// </summary>
        public string ProvinceID { get; set; }
        /// <summary>
        /// 市ID
        /// </summary>
        public string CityID { get; set; }
        /// <summary>
        /// 县区ID
        /// </summary>
        public string CountyID { get; set; }
        /// <summary>
        /// 图标地址url 全路径
        /// </summary>
        public string IconUrl { get; set; }
        /// <summary>
        /// 链接地址
        /// </summary>
        public string LinkUrl { get; set; }
    }
}


