//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class syssmstemplate
    {
        /// <summary>
        /// 编号
        /// </summary>
        public int TemplateID { get; set; }
        /// <summary>
        /// 模版编号
        /// </summary>
        public string TemplateCode { get; set; }
        /// <summary>
        /// 模版名称
        /// </summary>
        public string TemplateName { get; set; }
        /// <summary>
        /// 模版内容
        /// </summary>
        public string TemplateContent { get; set; }
        /// <summary>
        /// 1 验证码 2 通知
        /// </summary>
        public int TemplateType { get; set; }
        /// <summary>
        /// 1 美味云 2 商家
        /// </summary>
        public int TemplateOwner { get; set; }
    }
}


