//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class sysversion
    {
        /// <summary>
        /// 版本编号
        /// </summary>
        public int VersionID { get; set; }
        /// <summary>
        /// 版本名称（免费版，收费版）
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 售价
        /// </summary>
        public decimal Price { get; set; }
        /// <summary>
        /// 餐桌最大数量
        /// </summary>
        public int TableMaxCount { get; set; }
        /// <summary>
        /// 打印机最大数量
        /// </summary>
        public int PrintMaxCount { get; set; }
        /// <summary>
        /// 收银端最大数量
        /// </summary>
        public int CashierMaxCount { get; set; }
        /// <summary>
        /// 最低分销价格
        /// </summary>
        public decimal MinDistribution { get; set; }
        /// <summary>
        /// 是否是一个版本可能是一个功能
        /// </summary>
        public int IsVersion { get; set; }
    }
}


