//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuscritique
    {
        /// <summary>
        /// 用户点评表ID(guid)
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public Nullable<int> UserId { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 综合评分
        /// </summary>
        public Nullable<decimal> TotalScore { get; set; }
        /// <summary>
        /// 描述评分
        /// </summary>
        public Nullable<int> DescribeScore { get; set; }
        /// <summary>
        /// 价格评分
        /// </summary>
        public Nullable<int> PriceScore { get; set; }
        /// <summary>
        /// 环境评分
        /// </summary>
        public Nullable<int> RestaurantScore { get; set; }
        /// <summary>
        /// 服务评分
        /// </summary>
        public Nullable<int> ServiceScore { get; set; }
        /// <summary>
        /// 评论信息
        /// </summary>
        public string Contents { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public Nullable<bool> IsDel { get; set; }
        /// <summary>
        /// 点评的订单ID
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image1 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image2 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image3 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image4 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image5 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image6 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image7 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image8 { get; set; }
        /// <summary>
        /// 评论图片1
        /// </summary>
        public string Image9 { get; set; }
        /// <summary>
        /// 是否显示
        /// </summary>
        public Nullable<bool> IsShow { get; set; }
    }
}


