//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuschainuserdetail
    {
        /// <summary>
        /// 返俑收益表
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 收益用户
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 标识
        /// </summary>
        public int Sign { get; set; }
        /// <summary>
        /// 返俑金额
        /// </summary>
        public decimal Data { get; set; }
        /// <summary>
        /// 返俑用户
        /// </summary>
        public int ChainUserId { get; set; }
        /// <summary>
        /// 返俑比例
        /// </summary>
        public decimal Scale { get; set; }
        /// <summary>
        /// 几级返俑
        /// </summary>
        public int Level { get; set; }
        /// <summary>
        /// 商家
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 商家返俑比例
        /// </summary>
        public decimal ShopScale { get; set; }
        /// <summary>
        /// 返俑时间
        /// </summary>
        public System.DateTime CreateDate { get; set; }
    }
}


