//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class cusorderfooddetail
    {
        /// <summary>
        /// 订单详情表中消费套餐详情ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 订单详情编号ID
        /// </summary>
        public string OrderDetailID { get; set; }
        /// <summary>
        /// 菜品ID
        /// </summary>
        public string FoodID { get; set; }
        /// <summary>
        /// 菜的名称
        /// </summary>
        public string FoodName { get; set; }
        /// <summary>
        /// 规格ID
        /// </summary>
        public string FoodSpecificationsID { get; set; }
        /// <summary>
        /// 规格名称
        /// </summary>
        public string FoodSpecificationsName { get; set; }
        /// <summary>
        /// 菜品类型编号
        /// </summary>
        public string FoodTypeID { get; set; }
        /// <summary>
        /// 菜品类型名称
        /// </summary>
        public string FoodTypeName { get; set; }
        /// <summary>
        /// 菜品属性
        /// </summary>
        public string FoodAttributeID { get; set; }
        /// <summary>
        /// 菜品属性编号
        /// </summary>
        public string FoodAttributeName { get; set; }
        /// <summary>
        /// 菜品添加类型（1正常点菜2赠送3退菜）
        /// </summary>
        public Nullable<int> AddType { get; set; }
        /// <summary>
        /// 加菜是 1 退菜 -1
        /// </summary>
        public int Sign { get; set; }
        /// <summary>
        /// 菜的数量
        /// </summary>
        public decimal FoodCount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int FoodStatus { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 下单时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 普通价格 
        /// </summary>
        public decimal PriceGeneral { get; set; }
        /// <summary>
        /// 会员价格
        /// </summary>
        public decimal PriceVip { get; set; }
        /// <summary>
        /// 外卖价
        /// </summary>
        public decimal PriceTakeOut { get; set; }
        /// <summary>
        /// 特价价格
        /// </summary>
        public decimal PriceSpecial { get; set; }
        /// <summary>
        /// 菜的计算价格（1 PriceGeneral 2 PriceVip 3PriceTakeOut 4PriceSpecial）
        /// </summary>
        public int PriceType { get; set; }
        /// <summary>
        /// 打印机ID
        /// </summary>

        public string PrinterID { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
    }
}


