//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class cusorderdetail
    {
        /// <summary>
        /// 订单详情表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 订单ID
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 名称 菜品名称 套餐名称 固定费用
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 类别 对应名称的类别 1菜品名称 2套餐名称 3固定费用
        /// </summary>
        public int Type { get; set; }
        /// <summary>
        /// 商品编号
        /// </summary>
        public string GoodsID { get; set; }
        /// <summary>
        /// 商品价格
        /// </summary>
        public decimal GoodsPrice { get; set; }
        /// <summary>
        /// 商品数量
        /// </summary>
        public decimal GoodsCount { get; set; }
        /// <summary>
        /// 小计
        /// </summary>
        public Nullable<decimal> GoodsTotalPrice { get; set; }
        /// <summary>
        /// 商品是否自助 0否 1是
        /// </summary>
        public bool GoodsIsSelfHelp { get; set; }
        /// <summary>
        /// 单份商品使用次数（计次卡专用）
        /// </summary>
        public int GoodsUsageCount { get; set; }
        /// <summary>
        /// 总共商品使用次数（计次卡专用）
        /// </summary>
        public int GoodsTotalUsageCount { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 下单时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}


