//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusorderpackagedetail
    {
        public string ID { get; set; }
        public string OrderDetailID { get; set; }
        public string FoodID { get; set; }
        public Nullable<decimal> FoodPrice { get; set; }
        public Nullable<int> FoodCount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string SellerID { get; set; }
        public string Title { get; set; }
        public string FoodTypeID { get; set; }
        public Nullable<int> AddType { get; set; }
        public Nullable<int> MakeType { get; set; }
        public Nullable<int> MakeCount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FoodTypeName { get; set; }
        public string FoodSpecificationsID { get; set; }
    }
}
