//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusorderpaydetail
    {
        public string ID { get; set; }
        public string OrderPayID { get; set; }
        public string PaySource { get; set; }
        public string BankNumber { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public Nullable<int> SuccessState { get; set; }
        public Nullable<int> PayType { get; set; }
        public string LinkMan { get; set; }
        public string LinkPhone { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
