//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class cusorder
    {
        /// <summary>
        /// 订单ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 下单用户ID
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 订单创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 订单价格
        /// </summary>
        public decimal OrderPrice { get; set; }
        /// <summary>
        /// 就餐人数
        /// </summary>
        public int PeopleCount { get; set; }
        /// <summary>
        /// 订单来源(1用户点餐3吧台点餐4服务员点餐)
        /// </summary>
        public int OrderSource { get; set; }
        /// <summary>
        /// 订单状态 11预存订单  21扫码提交订单 31确认订单 41完成订单 51取消订单 
        /// </summary>
        public int OrderState { get; set; }
        /// <summary>
        /// 订单退款状态(0未处理不是退单1是退单)
        /// </summary>
        public int RefundState { get; set; }
        /// <summary>
        /// 订单点评状态（1已点评0未点评）
        /// </summary>
        public Nullable<int> CritiqueState { get; set; }
        /// <summary>
        /// 订单备注
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 餐桌ID
        /// </summary>
        public string TableID { get; set; }
        /// <summary>
        /// 餐桌名称
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 订单排队号（外卖排队用）
        /// </summary>
        public int OrderNo { get; set; }
        /// <summary>
        /// 就餐时段（1早餐2午餐3晚餐4夜宵）
        /// </summary>
        public int MealTimeSpan { get; set; }
        /// <summary>
        /// 是否外卖（1是0否）
        /// </summary>
        public int IsTakeOut { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 工作人员ID（服务员）
        /// </summary>
        public string SellerID { get; set; }
        /// <summary>
        /// 是否清台（清台时候用0否1是）
        /// </summary>
        public Nullable<int> IsClear { get; set; }
        /// <summary>
        /// 是否下单不起菜0否1是
        /// </summary>
        public Nullable<int> IsNoUpFood { get; set; }
        /// <summary>
        /// 预存订单时间
        /// </summary>
        public Nullable<System.DateTime> PrestoreOrderTime { get; set; }
        /// <summary>
        /// 扫码提交订单时间
        /// </summary>
        public Nullable<System.DateTime> SubmitOrderTime { get; set; }
        /// <summary>
        /// 确认下单时间
        /// </summary>
        public Nullable<System.DateTime> ConfirmOrderTime { get; set; }
        /// <summary>
        /// 完成时间
        /// </summary>
        public Nullable<System.DateTime> CompleteOrderTime { get; set; }
        /// <summary>
        /// 取消订单时间
        /// </summary>
        public Nullable<System.DateTime> CancelOrderTime { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public decimal FoodCount { get; set; }

        /// <summary>
        /// 预定金额
        /// </summary>
        public Nullable<decimal> ResourMoney { get; set; }
        /// <summary>
        /// 是否使用优惠促销 0 未使用 1使用
        /// </summary>
        public bool IsUsedDiscount { get; set; }
        /// <summary>
        /// 折扣类型
        /// </summary>
        public int DiscountType { get; set; }
        /// <summary>
        /// 促销规则名称
        /// </summary>
        public string DiscountName { get; set; }
        /// <summary>
        /// 满多少
        /// </summary>
        public decimal DiscountFullAmount { get; set; }
        /// <summary>
        /// 减多少
        /// </summary>
        public decimal DiscountSetAmount { get; set; }
        /// <summary>
        /// 折扣比例 0.85 8.5折
        /// </summary>
        public decimal DiscountScale { get; set; }
        /// <summary>
        /// 折扣数量
        /// </summary>
        public decimal DiscountAmount { get; set; }
        /// <summary>
        /// 优惠字符串
        /// </summary>
        public string DiscountAmountStr { get; set; }
        /// <summary>
        /// 口味,以逗开的形式存储
        /// </summary>
        public string FoodTaste1Remark { get; set; }
        /// <summary>
        /// 忌口,以逗开的形式存储
        /// </summary>
        public string FoodTaste2Remark { get; set; }

        /// <summary>
        /// 出库单自动核减( 0:未核减 1：已核减 2：核减失败)
        /// </summary>

        public int AutoCheckState { get; set; }
    }
}


