//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusordercus
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public string ShopID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> MealTime { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> PeopleCount { get; set; }
        public Nullable<int> OrderSource { get; set; }
        public string VCode { get; set; }
        public Nullable<System.DateTime> PayFinishTime { get; set; }
        public Nullable<int> PayState { get; set; }
        public Nullable<int> ConsumeState { get; set; }
        public Nullable<int> RefundState { get; set; }
        public Nullable<int> CritiqueState { get; set; }
        public string IDKey { get; set; }
        public string Introduction { get; set; }
        public string TableID { get; set; }
        public string DiscountStr { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> MealTimeSpan { get; set; }
        public Nullable<int> IsTakeOut { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
