//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusorderrabate
    {
        /// <summary>
        /// 订单返利表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 下单用户ID
        /// </summary>
        public Nullable<int> UserID { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 下单时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 订单价格
        /// </summary>
        public Nullable<decimal> OrderPrice { get; set; }
        /// <summary>
        /// 一级返利用户ID
        /// </summary>
        public string RabateUserID1 { get; set; }
        /// <summary>
        /// 一级返利金额
        /// </summary>
        public Nullable<decimal> RabateMoney1 { get; set; }
        /// <summary>
        /// 二级返利用户ID
        /// </summary>
        public string RabateUserID2 { get; set; }
        /// <summary>
        /// 二级返利金额
        /// </summary>
        public Nullable<decimal> RabateMoney2 { get; set; }
        /// <summary>
        /// 三级返利用户ID
        /// </summary>
        public string RabateUserID3 { get; set; }
        /// <summary>
        /// 三级返利金额
        /// </summary>
        public Nullable<decimal> RabateMoney3 { get; set; }
    }
}


