//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class cuspayment
    {
        /// <summary>
        /// 订单支付表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 支付完成时间
        /// </summary>
        public Nullable<System.DateTime> PayFinishTime { get; set; }
        /// <summary>
        /// 订单支付状态(0未完成1支付完成)
        /// </summary>
        public int PayState { get; set; }
        /// <summary>
        /// 总价(菜品计算下的总金额）
        /// </summary>
        public decimal TotalPrice { get; set; }
        /// <summary>
        /// 支付次数
        /// </summary>
        public int PayCount { get; set; }
        /// <summary>
        /// 是否使用会员卡(0未使用 1使用)
        /// </summary>
        public bool IsUsedCard { get; set; }
        /// <summary>
        /// 会员卡类型
        /// </summary>
        public int CardTypeID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CardID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CardRuleName { get; set; }
        /// <summary>
        /// 折扣比例 0.85 8.5折
        /// </summary>
        public decimal CardDiscountScale { get; set; }
        /// <summary>
        /// 卡的折扣金额
        /// </summary>
        public decimal CardDiscountAmount { get; set; }
        /// <summary>
        /// 是否使用优惠促销 0 未使用 1使用
        /// </summary>
        public bool IsUsedDiscount { get; set; }
        /// <summary>
        /// 折扣类型
        /// </summary>
        public int DiscountType { get; set; }
        /// <summary>
        /// 促销规则名称
        /// </summary>
        public string DiscountName { get; set; }
        /// <summary>
        /// 满多少
        /// </summary>
        public decimal DiscountFullAmount { get; set; }
        /// <summary>
        /// 减多少
        /// </summary>
        public decimal DiscountSetAmount { get; set; }
        /// <summary>
        /// 折扣比例 0.85 8.5折
        /// </summary>
        public decimal DiscountScale { get; set; }
        /// <summary>
        /// 折扣数量
        /// </summary>
        public decimal DiscountAmount { get; set; }
        /// <summary>
        /// 订单备注
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 抹零
        /// </summary>
        public decimal SmallDiscount { get; set; }
        /// <summary>
        /// 应付金额（总金额-会员卡规则优惠的金额-优惠促销优惠的金额-抹零）
        /// </summary>
        public decimal Payable { get; set; }
        /// <summary>
        /// 实付
        /// </summary>

        public decimal Paid { get; set; }
        /// <summary>
        /// 结账时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 收银员ID(服务员或吧台)
        /// </summary>
        public string SellerID { get; set; }
    }
}


