//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuspaymentassociatedorders
    {
        /// <summary>
        /// 支付关联订单
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 订单编号
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 支付表编号
        /// </summary>
        public string PaymentID { get; set; }
        /// <summary>
        /// 商家编号
        /// </summary>
        public string ShopId { get; set; }
    }
}


