//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class cuspaymentdetail
    {
        /// <summary>
        /// 订单支付详情ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属订单支付ID
        /// </summary>
        public string PaymentID { get; set; }
        /// <summary>
        /// 支付类型
        /// </summary>
        public int PaymentTypeID { get; set; }
        /// <summary>
        /// 支付来源
        /// </summary>
        public string PaySource { get; set; }
        /// <summary>
        /// 付款码
        /// </summary>
        public string BatchId { get; set; }
        /// <summary>
        /// 应收金额 数量
        /// </summary>
        public decimal Amount { get; set; }
        /// <summary>
        /// 欠款人
        /// </summary>
        public string DebtName { get; set; }
        /// <summary>
        /// 欠款人手机
        /// </summary>
        public string DebtPhone { get; set; }
        /// <summary>
        /// 支付时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 实收金额
        /// </summary>
        public decimal PayInAmount { get; set; }
        /// <summary>
        /// 找零（实收-应收）
        /// </summary>
        public decimal Change { get; set; }
        /// <summary>
        /// 支付次数序列 1 第一次 2 第二次
        /// </summary>

        public int PayCountSequence { get; set; }
        /// <summary>
        /// 记录免单金额
        /// </summary>

        public decimal FreeAmount { get; set; }
        /// <summary>
        /// 支付订单备注  ---  
        /// </summary>

        public string Remark { get; set; }
    }
}


