//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusrepaymentdetail
    {
        /// <summary>
        ///  
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 还款表编号
        /// </summary>
        public string RePaymentID { get; set; }
        /// <summary>
        /// 支付表编号
        /// </summary>
        public string PaymentID { get; set; }
        /// <summary>
        /// 支付详情表编号
        /// </summary>
        public string PaymentDetailID { get; set; }
        
    }
}


