//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class cususerjinbi
    { 
        /// <summary>
        /// 用户编号
        /// </summary> 
        public int UserId { get; set; }
        /// <summary>
        /// 金币
        /// </summary>
        public decimal Jinbi { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime TimeStamp { get; set; }
    }
}


