//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cususer
    {
        /// <summary>
        /// 用户表ID 数据来源于cusfreeuserid
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 用户名 可登录使用
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 昵称 给端上显示时使用
        /// </summary>
        public string NickName { get; set; }
        /// <summary>
        /// 手机 登录的时候使用手机号登录
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 登陆密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 是否可用 1正常使用 0 不可使用（无法登录，需要提示）
        /// </summary>
        public int IsAvailable { get; set; }
        /// <summary>
        /// 父ID 如果没有父编号，则为0
        /// </summary>
        public int ParentUserId { get; set; }
        /// <summary>
        /// 是否是新用户（1是其他否）首单减免使用
        /// </summary>
        public bool IsNew { get; set; }
    }
}


