//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cususerdetail
    {
        /// <summary>
        /// 用户详情ID
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 头像地址
        /// </summary>
        public string HeadImgUrl { get; set; }
        /// <summary>
        /// QQ
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 真实姓名
        /// </summary>
        public string RealName { get; set; }
        /// <summary>
        /// 性别 0 保密 1 男 2 女
        /// </summary>
        public int Sex { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public Nullable<System.DateTime> Birthday { get; set; }
        /// <summary>
        /// 省ID
        /// </summary>
        public string ProvinceID { get; set; }
        /// <summary>
        /// 市ID
        /// </summary>
        public string CityID { get; set; }
        /// <summary>
        /// 县区ID
        /// </summary>
        public string CountyID { get; set; }
        /// <summary>
        /// 商圈ID
        /// </summary>
        public string AreaID { get; set; }
        /// <summary>
        /// 客户地址
        /// </summary>
        public string AddressInfo { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 管理区域类型（1全国2省3市4县区5商圈，其他无）
        /// </summary>
        public Nullable<int> ManagerAreaType { get; set; }
        /// <summary>
        /// 经验值
        /// </summary>
        public int Exp { get; set; }
        /// <summary>
        /// 用户等级ID
        /// </summary>
        public string UserLevelID { get; set; }
    }
}


