//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class procompany
    {
        /// <summary>
        /// 代理公司ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 代理公司名称
        /// </summary>
        public string CompanyName { get; set; }
        /// <summary>
        /// 地图经度
        /// </summary>
        public Nullable<double> MapX { get; set; }
        /// <summary>
        /// 地图维度
        /// </summary>
        public Nullable<double> MapY { get; set; }
        /// <summary>
        /// 凭证图1
        /// </summary>
        public string CredentialsImg1 { get; set; }
        /// <summary>
        /// 凭证图2
        /// </summary>
        public string CredentialsImg2 { get; set; }
        /// <summary>
        /// 凭证图3
        /// </summary>
        public string CredentialsImg3 { get; set; }
        /// <summary>
        /// 凭证图4
        /// </summary>
        public string CredentialsImg4 { get; set; }
        /// <summary>
        /// 凭证图5
        /// </summary>
        public string CredentialsImg5 { get; set; }
        /// <summary>
        /// 删除状态
        /// </summary>
        public Nullable<int> IsDel { get; set; }
        /// <summary>
        /// 锁定状态
        /// </summary>
        public Nullable<int> IsLock { get; set; }
        /// <summary>
        /// 联系人
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 手机
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string Tel { get; set; }
        /// <summary>
        /// qq
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 省ID
        /// </summary>
        public string ProvinceID { get; set; }
        /// <summary>
        /// 市ID
        /// </summary>
        public string CityID { get; set; }
        /// <summary>
        /// 县区ID
        /// </summary>
        public string CountyID { get; set; }
        /// <summary>
        /// 商圈ID
        /// </summary>
        public string AreaID { get; set; }
        /// <summary>
        /// 详细地址
        /// </summary>
        public string AddressInfo { get; set; }
        /// <summary>
        /// 代理区域类型（1全国2省3市4县区5商圈，其他无）
        /// </summary>
        public Nullable<int> ManagerAreaType { get; set; }
        /// <summary>
        /// 创建管理员ID
        /// </summary>
        public string CreateManagerID { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 使用结束时间
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 代理规模ID
        /// </summary>
        public string ScaleID { get; set; }
        /// <summary>
        /// 代理性质ID
        /// </summary>
        public string PropertyID { get; set; }
        /// <summary>
        /// 拥有者代理人员ID
        /// </summary>
        public string OwnProxyID { get; set; }
        /// <summary>
        /// 支付宝账户
        /// </summary>
        public string BankAlipay { get; set; }
        /// <summary>
        /// 微信账户
        /// </summary>
        public string BankWeiXin { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 代理公司提成点数（例如百分之一填0.01）
        /// </summary>
        public Nullable<double> PercentageProxy { get; set; }
        /// <summary>
        /// 父代理公司ID
        /// </summary>
        public string ParaentCompanyID { get; set; }
        /// <summary>
        /// 代理公司余额
        /// </summary>
        public Nullable<decimal> ProxyMoney { get; set; }
    }
}


