//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class prorole_pemit
    {
        /// <summary>
        /// 代理角色权限关系表
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 代理角色ID
        /// </summary>
        public string ProRoleID { get; set; }
        /// <summary>
        /// 代理权限ID
        /// </summary>
        public string ProPemitID { get; set; }
    }
}


