//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusorderpaydetail
    {
        /// <summary>
        /// 订单支付详情ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属订单支付ID
        /// </summary>
        public string OrderPayID { get; set; }
        /// <summary>
        /// 支付来源（这个按照数据表定义的走）
        /// </summary>
        public string PaySource { get; set; }
        /// <summary>
        /// 支付账号
        /// </summary>
        public string BankNumber { get; set; }
        /// <summary>
        /// 支付金额
        /// </summary>
        public Nullable<decimal> PayMoney { get; set; }
        /// <summary>
        /// 成功状态（1成功2其他未成功）
        /// </summary>
        public Nullable<int> SuccessState { get; set; }
        /// <summary>
        /// 支付类型（1正常消费2挂账还款）
        /// </summary>
        public Nullable<int> PayType { get; set; }
        /// <summary>
        /// 还款人
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 还款人手机
        /// </summary>
        public string LinkPhone { get; set; }
        /// <summary>
        /// 支付时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 是否删除（1是0否）反结账用
        /// </summary>
        public Nullable<int> IsDel { get; set; }
    }
}


