//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

//namespace YRD.Dao
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class cusorderpackagedetail
//    {
//        /// <summary>
//        /// 订单详情表中消费套餐详情ID
//        /// </summary>
//        public string ID { get; set; }
//        /// <summary>
//        /// 订单ID
//        /// </summary>
//        public string OrderDetailID { get; set; }
//        /// <summary>
//        /// 菜品ID
//        /// </summary>
//        public string FoodID { get; set; }
//        /// <summary>
//        /// 菜品价格
//        /// </summary>
//        public Nullable<decimal> FoodPrice { get; set; }
//        /// <summary>
//        /// 数量
//        /// </summary>
//        public Nullable<int> FoodCount { get; set; }
//        /// <summary>
//        /// 小计
//        /// </summary>
//        public Nullable<decimal> TotalPrice { get; set; }
//        /// <summary>
//        /// 工作人员ID（厨师）
//        /// </summary>
//        public string SellerID { get; set; }
//        /// <summary>
//        /// 菜品名称或者固定费用名称
//        /// </summary>
//        public string Title { get; set; }
//        /// <summary>
//        /// 菜品类型ID
//        /// </summary>
//        public string FoodTypeID { get; set; }
//        /// <summary>
//        /// 菜品添加类型（1正常点菜2赠送3退菜）
//        /// </summary>
//        public Nullable<int> AddType { get; set; }
//        /// <summary>
//        /// 上菜状态（1制作中2已上菜3部分上）
//        /// </summary>
//        public Nullable<int> MakeType { get; set; }
//        /// <summary>
//        /// 已上数量
//        /// </summary>
//        public Nullable<int> MakeCount { get; set; }
//        /// <summary>
//        /// 添加日期
//        /// </summary>
//        public Nullable<System.DateTime> CreateDate { get; set; }
//        /// <summary>
//        /// 菜品类型名称
//        /// </summary>
//        public string FoodTypeName { get; set; }
//        /// <summary>
//        /// 规格ID
//        /// </summary>
//        public string FoodSpecificationsID { get; set; }
//    }
//}


