//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusorderpay
    {
        /// <summary>
        /// 订单支付表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 订单编号
        /// </summary>
        public string OrderID { get; set; }
        /// <summary>
        /// 支付用户ID(返利用)
        /// </summary>
        public string PayUserID { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 总价计算下的金额
        /// </summary>
        public decimal TotalPrice { get; set; }
        /// <summary>
        /// 支付完成时间
        /// </summary>
        public Nullable<System.DateTime> PayFinishTime { get; set; }
        /// <summary>
        /// 订单支付状态(1全额支付2部分支付3全额挂账4部分挂账5免单)
        /// </summary>
        public Nullable<int> PayState { get; set; }
        /// <summary>
        /// 订单备注
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 实际支付金额
        /// </summary>
        public Nullable<decimal> PayPrice { get; set; }
        /// <summary>
        /// 优惠金额
        /// </summary>
        public Nullable<decimal> DiscountPrice { get; set; }
        /// <summary>
        /// 餐后劵ID
        /// </summary>
        public string CouponMealBackID { get; set; }
        /// <summary>
        /// 餐后劵金额
        /// </summary>
        public Nullable<decimal> CouponMealBackPrice { get; set; }
        /// <summary>
        /// 推广劵ID
        /// </summary>
        public string CouponExtensionID { get; set; }
        /// <summary>
        /// 推广劵金额
        /// </summary>
        public Nullable<decimal> CouponExtensionPrice { get; set; }
        /// <summary>
        /// 折扣（八折就是0.80）
        /// </summary>
        public Nullable<decimal> Discount { get; set; }
        /// <summary>
        /// 用户使用的余额
        /// </summary>
        public Nullable<decimal> UserMoney { get; set; }
        /// <summary>
        /// 抹零
        /// </summary>
        public Nullable<decimal> SmallDiscount { get; set; }
        /// <summary>
        /// 支付来源((1远程2扫码3吧台4服务员)
        /// </summary>
        public Nullable<int> PaySource { get; set; }
        /// <summary>
        /// 优惠字符串
        /// </summary>
        public string DiscountStr { get; set; }
        /// <summary>
        /// 下单时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 收银员ID(服务员或吧台)
        /// </summary>
        public string SellerID { get; set; }
        /// <summary>
        /// 挂账人
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 挂账人手机
        /// </summary>
        public string LinkPhone { get; set; }
    }
}


