//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;

    public partial class cusreserve
    {
        /// <summary>
        /// 用户预定表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 所属用户ID
        /// </summary>
        public string UserID { get; set; }
        /// <summary>
        /// 预定店铺ID
        /// </summary>
        public string ShopID { get; set; }
        /// <summary>
        /// 就餐时间
        /// </summary>
        public System.DateTime MealTime { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Introduction { get; set; }
        /// <summary>
        /// 预定状态（ 1预定成功 2预定失败 3商家取消）
        /// </summary>
        public int ReserveState { get; set; }
        /// <summary>
        /// 预定人数
        /// </summary>
        public int ReserveCount { get; set; }
        /// <summary>
        /// 餐桌ID
        /// </summary>
        public string TableID { get; set; }
        /// <summary>
        /// 客户名称
        /// </summary>
        public string CustomerName { get; set; }
        /// <summary>
        /// 客户手机号
        /// </summary>
        public string CustomerPhone { get; set; }
        /// <summary>
        /// 是否同意大厅餐位（0不同意1同意）
        /// </summary>
        public int IsAgreeHell { get; set; }
        /// <summary>
        /// 定金
        /// </summary>
        public decimal DepositPrice { get; set; }
        /// <summary>
        /// 退订金
        /// </summary>
        public decimal BackDepositPrice { get; set; }
        /// <summary>
        /// 支付方式（1现金2支付宝3微信4银行卡5支票6转账）
        /// </summary>
        public int PayMode { get; set; }
        /// <summary>
        /// 是否发送短信（1是0否）
        /// </summary>
        public int IsSms { get; set; }
        /// <summary>
        /// 就餐时段（1早上2中午3晚上4夜宵）
        /// </summary>
        public int MealTimeSpan { get; set; }
        /// <summary>
        /// 预定来源（1电话2APP3到店）
        /// </summary>
        public int OrderSource { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public int Sex { get; set; }
        /// <summary>
        /// 确认时间
        /// </summary>
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        /// <summary>
        /// 取消时间
        /// </summary>
        public Nullable<System.DateTime> CancelTime { get; set; }
        /// <summary>
        /// 1 服务员取消 2系统过期取消
        /// </summary>
        public int CancelType { get; set; }
        /// <summary>
        /// 取消原因
        /// </summary>
        public string CancelReason { get; set; }
        /// <summary>
        /// 收银员ID
        /// </summary>
        public string SellerID { get; set; }
    }
}


