//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class procompany_area
    {
        /// <summary>
        /// 代理公司代理区域关系表
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 代理公司ID
        /// </summary>
        public string CompanyID { get; set; }
        /// <summary>
        /// 区域ID
        /// </summary>
        public string SysAreaID { get; set; }
    }
}


