//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class procompanyrabate
    {
        /// <summary>
        /// 代理返利记录ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 代理公司ID
        /// </summary>
        public string CompanyID { get; set; }
        /// <summary>
        /// 下单时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 返利金额
        /// </summary>
        public Nullable<decimal> RabateMoney { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        public Nullable<System.DateTime> StartTime { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        public string Contents { get; set; }
    }
}


