//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class promanagerdetail
    {
        /// <summary>
        /// 代理管理员详情ID（和代理管理员ID一样）
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 手机
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 固话
        /// </summary>
        public string Tel { get; set; }
        /// <summary>
        /// QQ
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 性别（1男0女）
        /// </summary>
        public Nullable<int> Gender { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public Nullable<System.DateTime> Birthday { get; set; }
        /// <summary>
        /// 管理的省ID
        /// </summary>
        public string ProvinceID { get; set; }
        /// <summary>
        /// 管理的市ID
        /// </summary>
        public string CityID { get; set; }
        /// <summary>
        /// 管理的县区ID
        /// </summary>
        public string CountyID { get; set; }
        /// <summary>
        /// 管理的商圈ID
        /// </summary>
        public string AreaID { get; set; }
        /// <summary>
        /// 办公住址
        /// </summary>
        public string AddressInfo { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 管理区域类型（1全国2省3市4县区5商圈，其他无）
        /// </summary>
        public Nullable<int> ManagerAreaType { get; set; }
        /// <summary>
        /// 创建管理员ID
        /// </summary>
        public string CreateManagerID { get; set; }
    }
}


