//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class promanager_selshop
    {
        /// <summary>
        /// 代理管理员负责店铺表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 代理管理员ID
        /// </summary>
        public string ProManagerID { get; set; }
        /// <summary>
        /// 店铺ID
        /// </summary>
        public string SelShopID { get; set; }
    }
}


