//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class promanager_role
    {
        /// <summary>
        /// 关系（代理管理员-代理角色）ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 系统角色ID
        /// </summary>
        public string SysRoleID { get; set; }
        /// <summary>
        /// 系统管理员ID
        /// </summary>
        public string SysManagerID { get; set; }
    }
}


