//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRD.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class propemit
    {
        /// <summary>
        /// 代理权限表ID
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 权限名
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 权限操作url
        /// </summary>
        public string Url { get; set; }
        /// <summary>
        /// 权限图片
        /// </summary>
        public string ImgUrl { get; set; }
        /// <summary>
        /// 权限父ID
        /// </summary>
        public string ParentID { get; set; }
        /// <summary>
        /// 权限父名称
        /// </summary>
        public string ParentTitle { get; set; }
        /// <summary>
        /// 是否是按钮
        /// </summary>
        public Nullable<int> IsMenu { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public Nullable<int> Sort { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public Nullable<int> IsDel { get; set; }
        /// <summary>
        /// 创建管理员ID
        /// </summary>
        public string CreateManagerID { get; set; }
        /// <summary>
        /// 代理公司ID
        /// </summary>
        public string CompanyID { get; set; }
    }
}


